SPHSolver Class Reference
creates fluid particles and perform SPH fluid simulation at every iteration
#include <SPHSolver.h>
Public Member Functions
SPHSolver ()
ctor
~SPHSolver ()
dtor
void updateFluid (EnvironmentAndRigidBody *io_environment, Integrate *_integrate)
update the fluid state at each timestep interval
std::vector< std::vector< ngl::Vector > > getFluidParticlePositionList ()
return the huge position list of all the fluid particles
std::vector< std::string > getFluidNameList ()
return the list storing the names of different fluid created
std::string getVisualizationType ()
return the shader name to be used for displaying the simulation data
std::vector< FluidParticle > getFluidParticleList ()
return the list of fluid particles being simulated
bool getDrawFluidParticles ()
returns the flag for drawing fluids
Private Member Functions
ngl::Vector calculateInterfaceTensionGradientComponent (ngl::Real _massPerDensity, ngl::Real _interfaceColourCoefficient, ngl::Vector _seperationVector)
calculate Interface Tension Gradient Component
ngl::Real calculateInterfaceTensionLaplacianComponent (ngl::Real _massPerDensity, ngl::Real _interfaceColourCoefficient, ngl::Real _seperationLength)
calculate Interface Tension Laplacian Component
ngl::Vector calculatePressureForceComponent (ngl::Real _fluidParticleScalerPressure, ngl::Real _fluidParticleDensity, ngl::Real _neighbourFluidParticleScalerPressure, ngl::Real _neighbourFluidDensity, ngl::Real _neighbourFluidParticleMass, ngl::Vector _seperationLength)
calculate Pressure Force Component
ngl::Vector calculateViscosityForceComponent (ngl::Real _massPerDensity, ngl::Vector _fluidParticleCurrentVelocity, ngl::Vector _neighbourFluidParticleCurrentVelocity, ngl::Real _seperationLength)
calculate Viscosity Force Component
ngl::Vector calculateSurfaceTennsionGradientComponent (ngl::Real _massPerDensity, ngl::Real _surfaceColourCoefficient, ngl::Vector _seperationVector)
calculate Surface Tension Gradient Component
ngl::Real calculateSurfaceTensionLaplacianComponent (ngl::Real _massPerDensity, ngl::Real _surfaceColourCoefficient, ngl::Real _seperationLength)
calculate Surface Tension Laplacian Component
ngl::Real KernelPoly (const ngl::Real _seperationLength)
calculate the poly 6 kernel
ngl::Vector KernelPolyGradient (const ngl::Vector _seperationVector)
calculate the poly 6 gradient kernel
ngl::Real KernelPolyLaplacian (const ngl::Real _seperationLength)
calculate the poly 6 laplacian kernel
ngl::Vector KernelPressureGradient (const ngl::Vector _seperationVector)
calculate the pressure (spiky) gradient kernel
ngl::Real KernelViscosityLaplacian (const ngl::Real _seperationLength)
calculate the viscosity laplacian kernel
ngl::Vector normalizeVector (const ngl::Vector _vector)
normalise a vector
int getFluidIdFromName (const std::string _name)
get a particle fluid id from its name
Private Attributes
std::vector< FluidParticle > m_fluidParticleList
list of particles making up the fluid simulation
std::vector< std::string > m_fluidNameList
ngl::Real m_smoothingLength
smoothing kernel length
SpatialHashing * m_spatialHashing
the neighbouring structure for the fluid particles
ngl::Real m_weightPoly
pre-calculated part of the poly 6 kernel
ngl::Real m_weightPolyGradient
pre-calculated part of the poly 6 gradient kernel
ngl::Real m_weightPolyLaplacian
pre-calculated part of the poly 6 laplacian kernel
ngl::Real m_weightPressureGradient
pre-calculated part of the pressure gradient kernel
ngl::Real m_weightViscosityLaplacian
pre-calculated part of the viscosity laplacian kernel
int m_iteration
iteration counter
std::string m_visualizationType
shading type of fluid particles
bool m_drawFluidParticles
flag to control to display fluid particles in OpenGL Window
Detailed Description
creates fluid particles and perform SPH fluid simulation at every iteration
Definition at line 23 of file SPHSolver.h.
Constructor & Destructor Documentation
SPHSolver::SPHSolver ()
ctor
Definition at line 11 of file SPHSolver.cpp.
References SimulationParameters::initialiseSPHFluidSolver(), m_drawFluidParticles, m_fluidNameList, m_fluidParticleList, m_iteration, m_smoothingLength, m_spatialHashing, m_visualizationType, m_weightPoly, m_weightPolyGradient, m_weightPolyLaplacian, m_weightPressureGradient, and m_weightViscosityLaplacian.
    //create particles and initialise parameters
    SimulationParameters::initialiseSPHFluidSolver
            (
                m_smoothingLength,
                m_fluidParticleList,
                m_visualizationType,
                m_drawFluidParticles,
                m_fluidNameList
            );
    //precompute kernel weight multipliers
    m_weightPoly = (315.0 / (64.0 * ngl::PI * pow(m_smoothingLength, 9)));
    m_weightPolyGradient = (-945.0 / (32.0 * ngl::PI * pow(m_smoothingLength, 9))
      );
    m_weightPolyLaplacian = (-945.0 / (32.0 * ngl::PI * pow(m_smoothingLength, 9)
      ));
    m_weightPressureGradient = (-45.0 / (ngl::PI * pow(m_smoothingLength, 6)));
    m_weightViscosityLaplacian = (45.0 / (ngl::PI * pow(m_smoothingLength, 6)));
    //create neighbouring structure
    m_spatialHashing = new SpatialHashing(m_fluidParticleList.size(),
      m_smoothingLength);
    m_iteration = 0;
// for (int i = 0; i < m_fluidNameList.size(); ++i)
//
// std::cout << "names of particle are :: " << m_fluidNameList[i] << std::endl
      ;
//
SPHSolver::~SPHSolver ()
dtor
Definition at line 41 of file SPHSolver.cpp.
References m_spatialHashing.
    //clean up
    std::cout << "Fluid SPHSolver Cleanup" << std::endl;
    //delete objects
    delete m_spatialHashing;
Member Function Documentation
ngl::Vector SPHSolver::calculateInterfaceTensionGradientComponent (ngl::Real _massPerDensity, ngl::Real _interfaceColourCoefficient, ngl::Vector _seperationVector) [private]
calculate Interface Tension Gradient Component
Parameters
$\leftarrow$ _massPerDensity mass per density of the fluid particle
$\leftarrow$ _interfaceColourCoefficient interface colour coefflicient of the fluid particle
$\leftarrow$ _seperationVector distance vector between the fluid particle and the neighbour fluid particle
Definition at line 379 of file SPHSolver.cpp.
References KernelPolyGradient().
    ngl::Vector interfaceTensionGradientComponent;
    ngl::Vector surfaceGradient = KernelPolyGradient(_seperationVector);
    interfaceTensionGradientComponent = _massPerDensity * _interfaceColourCoeffic
      ient * surfaceGradient;
    return interfaceTensionGradientComponent;
ngl::Real SPHSolver::calculateInterfaceTensionLaplacianComponent (ngl::Real _massPerDensity, ngl::Real _interfaceColourCoefficient, ngl::Real _seperationLength) [private]
calculate Interface Tension Laplacian Component
Parameters
$\leftarrow$ _massPerDensity mass per density of the fluid particle
$\leftarrow$ _interfaceColourCoefficient interface colour coefflicient of the fluid particle
$\leftarrow$ _seperationLength amplitube of the distance vector between the fluid particle and the neighbour fluid particle
Definition at line 391 of file SPHSolver.cpp.
References KernelPolyLaplacian().
    ngl::Real interfaceTensionLaplacianComponent;
    ngl::Real surfaceLaplacian = KernelPolyLaplacian(_seperationLength);
    interfaceTensionLaplacianComponent = _massPerDensity * _interfaceColourCoeffi
      cient * surfaceLaplacian;
    return interfaceTensionLaplacianComponent;
ngl::Vector SPHSolver::calculatePressureForceComponent (ngl::Real _fluidParticleScalerPressure, ngl::Real _fluidParticleDensity, ngl::Real _neighbourFluidParticleScalerPressure, ngl::Real _neighbourFluidDensity, ngl::Real _neighbourFluidParticleMass, ngl::Vector _seperationLength) [private]
calculate Pressure Force Component
Parameters
$\leftarrow$ _fluidParticleScalerPressure
$\leftarrow$ _fluidParticleDensity density of the fluid particle
$\leftarrow$ _neighbourFluidParticleScalerPressure
$\leftarrow$ _neighbourFluidDensity density of the neighbour fluid particle
$\leftarrow$ _neighbourFluidParticleMass mass of the neighbour fluid particle
$\leftarrow$ _seperationLength distance vector between the fluid particle and the neighbour fluid particle
Definition at line 260 of file SPHSolver.cpp.
References KernelPressureGradient().
      ngl::Vector pressureForceComponent = 0;
      ngl::Real _fluidParticleDensitySquared = pow (_fluidParticleDensity,2);
      ngl::Real _neighbourFluidParticleDensitySquared = pow(_neighbourFluidPartic
      leDensity,2);
      ngl::Vector pressureGradient = KernelPressureGradient(_seperationVector);
      pressureForceComponent = ((_fluidParticleScalerPressure / _fluidParticleDen
      sitySquared) + (_neighbourFluidParticleScalerPressure/_neighbourFluidParticleDens
      itySquared))
                            * _neighboutFluidParticleMass * pressureGradient;
      return pressureForceComponent;
ngl::Vector SPHSolver::calculateSurfaceTennsionGradientComponent (ngl::Real _massPerDensity, ngl::Real _surfaceColourCoefficient, ngl::Vector _seperationVector) [private]
calculate Surface Tension Gradient Component
Parameters
$\leftarrow$ _massPerDensity mass per density of the fluid particle
$\leftarrow$ _surfaceColourCoefficient surface colour coefficient of the fluid particle
$\leftarrow$ _seperationVector distance vector between the fluid particle and the neighbour fluid particle
Definition at line 299 of file SPHSolver.cpp.
References KernelPolyGradient().
    ngl::Vector surfaceTensionGradientComponent = 0;
    ngl::Vector surfaceGradient = KernelPolyGradient(_seperationVector);
    surfaceTensionGradientComponent = _massPerDensity * _surfaceColourCoefficient
       * surfaceGradient;
    return surfaceTensionGradientComponent;
ngl::Real SPHSolver::calculateSurfaceTensionLaplacianComponent (ngl::Real _massPerDensity, ngl::Real _surfaceColourCoefficient, ngl::Real _seperationLength) [private]
calculate Surface Tension Laplacian Component
Parameters
$\leftarrow$ _massPerDensity mass per density of the fluid particle
$\leftarrow$ _surfaceColourCoefficient surface colour coefficient of the fluid particle
$\leftarrow$ _seperationLength amplitude of the distance vector between the fluid particle and neighbour fluid particle
Definition at line 314 of file SPHSolver.cpp.
References KernelPolyLaplacian().
    ngl::Real surfaceTensionLaplacianComponent = 0;
    ngl::Real surfaceLaplacian = KernelPolyLaplacian(_seperationLength);
    surfaceTensionLaplacianComponent = _massPerDensity * _surfaceColourCoefficien
      t * surfaceLaplacian;
    return surfaceTensionLaplacianComponent;
ngl::Vector SPHSolver::calculateViscosityForceComponent (ngl::Real _massPerDensity, ngl::Vector _fluidParticleCurrentVelocity, ngl::Vector _neighbourFluidParticleCurrentVelocity, ngl::Real _seperationLength) [private]
calculate Viscosity Force Component
Parameters
$\leftarrow$ _massPerDensity mass per density of the fluid particle
$\leftarrow$ _fluidParticleCurrentVelocity current velocity of the fluid particle
$\leftarrow$ _neighbourFluidParticleCurrentVelocity current velocity of the neighbour fluid particle
$\leftarrow$ _seperationLength amplitube of the distance vector between fluid particle and the neighbour fluid particle
Definition at line 283 of file SPHSolver.cpp.
References KernelViscosityLaplacian().
    ngl::Vector viscosityForceComponent = 0;
    ngl::Real viscosityLaplacian = KernelViscosityLaplacian(_seperationLength);
    viscosityForceComponent = _massPerDensity * (_neighbourFluidParticleCurrentVe
      locity - _fluidParticleCurrentVelocity) * viscosityLaplacian;
    return viscosityForceComponent;
bool SPHSolver::getDrawFluidParticles () [inline]
returns the flag for drawing fluids
Definition at line 54 of file SPHSolver.h.
References m_drawFluidParticles.
return m_drawFluidParticles;
int SPHSolver::getFluidIdFromName (const std::string _name) [private]
get a particle fluid id from its name
Parameters
$\leftarrow$ _name the fluid name
std::vector<std::string> SPHSolver::getFluidNameList () [inline]
return the list storing the names of different fluid created
Definition at line 45 of file SPHSolver.h.
References m_fluidNameList.
return m_fluidNameList;
std::vector<FluidParticle> SPHSolver::getFluidParticleList () [inline]
return the list of fluid particles being simulated
Definition at line 51 of file SPHSolver.h.
References m_fluidParticleList.
return m_fluidParticleList;
std::vector< std::vector< ngl::Vector > > SPHSolver::getFluidParticlePositionList ()
return the huge position list of all the fluid particles
Definition at line 403 of file SPHSolver.cpp.
References m_fluidNameList, and m_fluidParticleList.
    std::vector<std::vector<ngl::Vector> > fluidParticlePositionsList;
    for (int i = 0; i< m_fluidNameList.size(); ++i)
    
        std::string name = m_fluidNameList[i];
        std::vector<ngl::Vector> positionList;
        positionList.reserve(m_fluidParticleList.size());
        for (int k = 0; k<m_fluidParticleList.size(); ++k)
        
            if (m_fluidParticleList[k].getName() == name)
            
                positionList.push_back(m_fluidParticleList[k].getCurrentPosition(
      ));
            
        
        fluidParticlePositionsList.push_back(positionList);
    
    return fluidParticlePositionsList;
std::string SPHSolver::getVisualizationType () [inline]
return the shader name to be used for displaying the simulation data
Definition at line 48 of file SPHSolver.h.
References m_visualizationType.
return m_visualizationType;
ngl::Real SPHSolver::KernelPoly (const ngl::Real _seperationLength) [private]
calculate the poly 6 kernel
Parameters
$\leftarrow$ _seperationLength amplitude of the distance vector between the fluid particle and neighbour fluid particle
Definition at line 330 of file SPHSolver.cpp.
References m_smoothingLength, and m_weightPoly.
    ngl::Real weight = m_weightPoly * (pow(pow(m_smoothingLength, 2) - pow(_seper
      ationLength, 2), 3));
    return weight;
ngl::Vector SPHSolver::KernelPolyGradient (const ngl::Vector _seperationVector) [private]
calculate the poly 6 gradient kernel
Parameters
$\leftarrow$ _seperationVector distance vector between the fluid particle and the neighbour fluid particle
Definition at line 337 of file SPHSolver.cpp.
References m_smoothingLength, and m_weightPolyGradient.
    ngl::Vector weight = 0;
    ngl::Real seperationLength = _seperationVector.length();
    weight = m_weightPolyGradient * _seperationVector * pow(pow(
      m_smoothingLength, 2) - pow(seperationLength, 2), 2);
    return weight;
ngl::Real SPHSolver::KernelPolyLaplacian (const ngl::Real _seperationLength) [private]
calculate the poly 6 laplacian kernel
Parameters
$\leftarrow$ _seperationLength amplitude of the distance vector between the fluid particle and neighbour fluid particle
Definition at line 347 of file SPHSolver.cpp.
References m_smoothingLength, and m_weightPolyLaplacian.
    ngl::Real weight = m_weightPolyLaplacian * (pow(m_smoothingLength, 2) - pow(_
      seperationLength, 2)) * ((3.0 * pow(m_smoothingLength, 2)) - (7.0 * pow(_seperati
      onLength, 2)));
    return weight;
ngl::Vector SPHSolver::KernelPressureGradient (const ngl::Vector _seperationVector) [private]
calculate the pressure (spiky) gradient kernel
Parameters
$\leftarrow$ _seperationVector distance vector between the fluid particle and the neighbour fluid particle
Definition at line 354 of file SPHSolver.cpp.
References m_smoothingLength, m_weightPressureGradient, and normalizeVector().
    ngl::Vector weight = 0;
    ngl::Real seperationLength = _seperationVector.length();
    weight = m_weightPressureGradient * pow(m_smoothingLength - seperationLength,
       2) * normalizeVector(_seperationVector);
    return weight;
ngl::Real SPHSolver::KernelViscosityLaplacian (const ngl::Real _seperationLength) [private]
calculate the viscosity laplacian kernel
Parameters
$\leftarrow$ _seperationLength amplitude of the distance vector between the fluid particle and neighbour fluid particle
Definition at line 364 of file SPHSolver.cpp.
References m_smoothingLength, and m_weightViscosityLaplacian.
    ngl::Real weight = m_weightViscosityLaplacian * (m_smoothingLength - _seperat
      ionLength);
    return weight;
ngl::Vector SPHSolver::normalizeVector (const ngl::Vector _vector) [private]
normalise a vector
Parameters
$\leftarrow$ _vector the vector to normalise
Definition at line 371 of file SPHSolver.cpp.
    ngl::Vector v = _vector;
    if (_vector.length() > 0.0001f) v.normalize();
    return v;
void SPHSolver::updateFluid (EnvironmentAndRigidBody * io_environment, Integrate * _integrate)
update the fluid state at each timestep interval
Parameters
$\leftrightarrow$ io_environment pointer to the enviornment class for performing collision check and resolution
$\leftarrow$ _integrate pointer to the integrate class used to perform integration
Definition at line 51 of file SPHSolver.cpp.
References EnvironmentAndRigidBody::checkCollision(), Particle::getCurrentPosition(), Particle::getCurrentVelocity(), FluidParticle::getDensity(), Particle::getId(), Particle::getMass(), FluidParticle::getScalerPressure(), Integrate::integrateNext(), and SimulationParameters::s_accelerationOfFreeFall.
    //clear neighbour map
    m_spatialHashing->clearHashmap();
#pragma omp parallel
    //refresh neighbour list
    m_spatialHashing->refreshHashmap(m_fluidParticleList);
#pragma omp parallel
#pragma omp for schedule(dynamic, 50)
    //density-pressure calculations
    for (int i = 0; i < m_fluidParticleList.size(); ++i)
    
        /*------Search and gather neighbour fluid particles for the current fluid
       particle-----------------------------------------*/
        std::vector<FluidParticle> neighbourList = m_spatialHashing->
      searchFluidParticleNeighbours(m_fluidParticleList[i].getCurrentPosition());
        /*-----Calculate Density-------------------------------------------------
      ---------------------------*/
        ngl::Real density = 0.0;
        for (int j = 0; j < neighbourList.size(); j++)
        
            //accumulate density
            density += neighbourList[j].getMass() * KernelPoly((
      m_fluidParticleList[i].getCurrentPosition() - neighbourList[j].getCurrentPosition
      ()).length());
        
        m_fluidParticleList[i].setDensity(density);
        /*-----Calculate Scaler Pressure Value-----------------------------------
      ------------------- */
        ngl::Real _scalerPressure = 0;
        _scalerPressure = m_fluidParticleList[i].getGasConstant() * (
      m_fluidParticleList[i].getDensity() - m_fluidParticleList[i].getRestDensity());
        m_fluidParticleList[i].setScalerPressure(_scalerPressure);
    
#pragma omp for schedule(dynamic, 50)
    /*----Calculation of Fluid Forces--------------------------------------------
      -------------------------*/
    for (int i = 0; i < m_fluidParticleList.size(); ++i)
    
        //getCurrentPosition() net forces accumulate
        m_fluidParticleList[i].resetForces();
        //get neighbours of current particle
        std::vector<FluidParticle> neighbourList = m_spatialHashing->
      searchFluidParticleNeighbours(m_fluidParticleList[i].getCurrentPosition());
        //calculate internal forces of current particle
        ngl::Real massPerDensity = 0;
        ngl::Vector seperationVector = 0;
        ngl::Real seperationLength = 0.0;
        ngl::Vector pressure = 0;
        ngl::Vector viscosity = 0;
        ngl::Vector surfaceGradient = 0;
        ngl::Real surfaceLaplacian = 0;
        ngl::Vector surfaceTensionGradient = 0;
        ngl::Real surfaceTensionLaplacian = 0;
        ngl::Vector interfaceTensionGradient = 0;
        ngl::Real interfaceTensionLaplacian = 0;
            for (int j = 0; j < neighbourList.size(); j++)
            
                /*----Get neighbour fluid particle-------------------------------
      ---*/
                FluidParticle neighbour = neighbourList[j];
                /*-----Calculating repetative values-----------------------------
      ----*/
                massPerDensity = neighbour.getMass() / neighbour.getDensity();
                seperationVector = m_fluidParticleList[i].getCurrentPosition() -
      neighbour.getCurrentPosition();
                seperationLength = seperationVector.length();
                /*------Calculating the pressure and viscosity force on the curre
      nt particle applied by the neighbour particle----------*/
                if (neighbour.getId() != m_fluidParticleList[i].getId())
                
                    /* Accumulate all the Pressure Force for the current fluid pa
      rticle */
                    pressure = pressure + calculatePressureForceComponent(
      m_fluidParticleList[i].getScalerPressure(),m_fluidParticleList[i].getDensity(),
                                                                          neighbo
      ur.getScalerPressure(),neighbour.getDensity(),
                                                                          neighbo
      ur.getMass(),seperationVector);
                    /* Accumulate all Viscosity Force for the current fluid parti
      cle */
                    viscosity = viscosity + calculateViscosityForceComponent(mass
      PerDensity,m_fluidParticleList[i].getCurrentVelocity(),
                                                                             neig
      hbour.getCurrentVelocity(),seperationLength);
                
                /* Accumulate Surface Tension Gradinet by calculating and accumul
      ating Surface Tension Gradient Component */
                surfaceTensionGradient = surfaceTensionGradient +
                                         
      calculateSurfaceTennsionGradientComponent(massPerDensity, m_fluidParticleList[i].
      getSurfaceColorCoefficient(),seperationVector);
                /* Accumulate Surface Tension Laplacian by calculating and accumu
      lating Surface Tension Laplacian Component */
                surfaceTensionLaplacian = surfaceTensionLaplacian +
                                          
      calculateSurfaceTensionLaplacianComponent(massPerDensity,m_fluidParticleList[i].g
      etSurfaceColorCoefficient(),seperationLength);
                /* Accumulate Interface Tension Gradient by calculating and accum
      ulating Interface Tension Gradient Component */
                interfaceTensionGradient = surfaceTensionGradient +
                                           
      calculateInterfaceTensionGradientComponent(massPerDensity,m_fluidParticleList[i].
      getInterfaceColorCoefficient(),seperationVector);
                /* Accumulate Interface Tension Laplacian by calculating and accu
      mulating Interface Tension Laplacian */
                interfaceTensionLaplacian = surfaceTensionLaplacian +
                                            
      calculateInterfaceTensionLaplacianComponent(massPerDensity,m_fluidParticleList[i]
      .getInterfaceColorCoefficient(),seperationLength);
            
    /*---Calculating and Setting Pressure Force ---------------------------------
      -----------------------------------------*/
    ngl::Vector pressureForce = 0;
    pressureForce = -1.0 * m_fluidParticleList[i].getDensity() * pressure;
    m_fluidParticleList[i].setPressureForce(pressureForce);
    /*---Calculating and Setting Viscosity Force --------------------------------
      -----------------------------------------*/
    ngl::Vector viscosityForce = 0;
    viscosityForce = viscosity * m_fluidParticleList[i].getViscosityConstant();
    m_fluidParticleList[i].setViscosityForce(viscosityForce);
    /*---Calculating and Setting Surface Tension Force --------------------------
      -------------------------------------------*/
    ngl::Vector surfaceTensionForce = 0;
    m_fluidParticleList[i].setSurfaceTensionForce(surfaceTensionForce);
    if (surfaceTensionGradient.length() > m_fluidParticleList[i].getSurfaceTensio
      nThreshold())
        
            surfaceTensionForce = -1.0 * m_fluidParticleList[i].getSurfaceTension
      Coefficient() * normalizeVector(surfaceTensionGradient) * surfaceTensionLaplacian
      ;
            m_fluidParticleList[i].setSurfaceTensionForce(surfaceTensionForce);
        
    /*---Calculating and Setting Interface Tension Force-------------------------
      ---------------------------------------------*/
    ngl::Vector interfaceTensionForce = 0;
    m_fluidParticleList[i].setInterfaceTensionForce(interfaceTensionForce);
        if (interfaceTensionGradient.length() > m_fluidParticleList[i].getInterfa
      ceTensionThreshold())
        
            interfaceTensionForce = -1.0 * m_fluidParticleList[i].getInterfaceTen
      sionCoefficient() * normalizeVector(interfaceTensionGradient) * interfaceTensionL
      aplacian;
            m_fluidParticleList[i].setInterfaceTensionForce(interfaceTensionForce
      );
        
    /*--- Calculating and setting the gravity force------------------------------
      ------------------------------------*/
    ngl::Vector gravityForce;
    ngl::Real _x = 0; ngl::Real _y = 0; ngl::Real _z = 0;
    _y = m_fluidParticleList[i].getDensity() *
      SimulationParameters::s_accelerationOfFreeFall;
    gravityForce.set(_x,_y,_z);
    m_fluidParticleList[i].setGravityForce(gravityForce);
    /*---Calculating and Setting Acceleration by calculating the total resultant
      forces and dividing then by density----------------------------*/
    ngl::Vector netForce = 0;
    netForce = m_fluidParticleList[i].getGravityForce() + m_fluidParticleList[i].
      getPressureForce() + m_fluidParticleList[i].getViscosityForce() +
               m_fluidParticleList[i].getSurfaceTensionForce() +
      m_fluidParticleList[i].getInterfaceTensionForce();
    m_fluidParticleList[i].setNetForce(netForce);
    ngl::Vector acceleration = 0;
    acceleration = m_fluidParticleList[i].getNetForce() / m_fluidParticleList[i].
      getDensity();
    m_fluidParticleList[i].updateAcceleration(acceleration);
    
#pragma omp for schedule(dynamic, 50)
    /*-----Integration of fluid and calculating its movement--------*/
    for (int i = 0; i < m_fluidParticleList.size(); ++i)
    
            _integrate->integrateNext(m_fluidParticleList[i]);
    
#pragma omp for schedule(dynamic, 50)
    /*----Checking and Handling Collision of Fluid with the Environment Box and R
      igid Bodies--------------*/
    for (int i = 0; i < m_fluidParticleList.size(); ++i)
    
        io_environment->checkCollision(m_fluidParticleList[i]);
    
Member Data Documentation
bool SPHSolver::m_drawFluidParticles [private]
flag to control to display fluid particles in OpenGL Window
Definition at line 91 of file SPHSolver.h.
std::vector<std::string> SPHSolver::m_fluidNameList [private]
Definition at line 61 of file SPHSolver.h.
std::vector<FluidParticle> SPHSolver::m_fluidParticleList [private]
list of particles making up the fluid simulation
Definition at line 59 of file SPHSolver.h.
int SPHSolver::m_iteration [private]
iteration counter
Definition at line 85 of file SPHSolver.h.
ngl::Real SPHSolver::m_smoothingLength [private]
smoothing kernel length
Definition at line 64 of file SPHSolver.h.
SpatialHashing* SPHSolver::m_spatialHashing [private]
the neighbouring structure for the fluid particles
Definition at line 67 of file SPHSolver.h.
std::string SPHSolver::m_visualizationType [private]
shading type of fluid particles
Definition at line 88 of file SPHSolver.h.
ngl::Real SPHSolver::m_weightPoly [private]
pre-calculated part of the poly 6 kernel
Definition at line 70 of file SPHSolver.h.
ngl::Real SPHSolver::m_weightPolyGradient [private]
pre-calculated part of the poly 6 gradient kernel
Definition at line 73 of file SPHSolver.h.
ngl::Real SPHSolver::m_weightPolyLaplacian [private]
pre-calculated part of the poly 6 laplacian kernel
Definition at line 76 of file SPHSolver.h.
ngl::Real SPHSolver::m_weightPressureGradient [private]
pre-calculated part of the pressure gradient kernel
Definition at line 79 of file SPHSolver.h.
ngl::Real SPHSolver::m_weightViscosityLaplacian [private]
pre-calculated part of the viscosity laplacian kernel
Definition at line 82 of file SPHSolver.h.
The documentation for this class was generated from the following files:
include/SPHSolver.h
src/SPHSolver.cpp