Render Class Reference
manages visulisation of simulation data generated by the sphSolver
#include <Render.h>
Public Member Functions
Render ()
ctor
void initialiseRender (EnvironmentAndRigidBody *_environment)
initialises the shaders and member variables of the class required to view the simulation data
void draw (EnvironmentAndRigidBody *_environment, SPHSolver *_solver, ngl::TransformStack _transformStack, ngl::Camera *_cam)
draws the simulation data on the OpenGL Window
void updateProjection (ngl::Camera *_cam)
updates the projection matrix for the shaders when the glWindow is resized
Private Attributes
ngl::BBox * m_bbox
pointer to ngl/BBox Class
Detailed Description
manages visulisation of simulation data generated by the sphSolver
Definition at line 21 of file Render.h.
Constructor & Destructor Documentation
Render::Render ()
ctor
Definition at line 5 of file Render.cpp.
Member Function Documentation
void Render::draw (EnvironmentAndRigidBody * _environment, SPHSolver * _solver, ngl::TransformStack _transformStack, ngl::Camera * _cam)
draws the simulation data on the OpenGL Window
Parameters
$\leftarrow$ _environment pointer to EnvironmentAndRigidBody Class
$\leftarrow$ _solver pointer to SPHSolver Class
$\leftarrow$ _transformStack transformation stack
$\leftarrow$ _cam pointer to ngl/Camera Class
Definition at line 50 of file Render.cpp.
References EnvironmentAndRigidBody::getBoundaryColour(), SPHSolver::getDrawFluidParticles(), SPHSolver::getFluidParticleList(), EnvironmentAndRigidBody::getObstacleEnabled(), EnvironmentAndRigidBody::getRBDSphereList(), SPHSolver::getVisualizationType(), and m_bbox.
// std::cout << "Enters the Render" << std::endl;
    std::string _shadername;
    std::vector<FluidParticle> _fluidParticleList;
    std::vector<Particle> _rbdSphereList;
    ngl::VBOPrimitives* prim = ngl::VBOPrimitives::instance();
    ngl::ShaderManager *shader=ngl::ShaderManager::instance();
    /*--- Drawing the Boundary Box -----------*/
    (*shader)["ConstantShading"]->use();
    shader->setShaderParam4f("ConstantShading", "inColor", _environment->
      getBoundaryColour().m_r, _environment->getBoundaryColour().m_g, _environment->
      getBoundaryColour().m_b ,1);
    shader->setShaderParamFromMatrix("ConstantShading","ViewMatrix",_cam->getMode
      lView());
    _transformStack.loadGlobalAndCurrentMatrixToShader("ConstantShading","ModelMa
      trix");
            m_bbox->draw();
    _fluidParticleList = _solver->getFluidParticleList();
    _rbdSphereList = _environment->getRBDSphereList();
    /*---Checking if the user wants to visualize the fluid particles------*/
    if (_solver->getDrawFluidParticles())
    
        if (_solver->getVisualizationType() == "3DShading")
        
            (*shader)["3DShading"]->use();
            _shadername = "3DShading";
            shader->setShaderParamFromMatrix(_shadername,"ViewMatrix",_cam->getMo
      delView());
        
        if (_solver->getVisualizationType() == "ConstantShading")
        
             (*shader)["ConstantShading"]->use();
            _shadername = "ConstantShading";
            shader->setShaderParamFromMatrix(_shadername,"ViewMatrix",_cam->getMo
      delView());
        
        /*--- Drawing the fluid particles--------*/
        _transformStack.pushTransform();
        
            for (int i = 0;i<_fluidParticleList.size();++i)
            
                ngl::Vector _position = _fluidParticleList[i].getCurrentPosition(
      );
                ngl::Real _scale = _fluidParticleList[i].getDrawRadius();
                ngl::Colour _colour = _fluidParticleList[i].getParticleColour();
                _transformStack.getCurrentTransform().setPosition(_position);
                _transformStack.getCurrentTransform().setScale(_scale,_scale,_sca
      le);
                shader->setShaderParam4f(_shadername, "inColor", _colour.m_r,_col
      our.m_g,_colour.m_b,1.0);
                shader->setShaderParamFromMatrix(_shadername,"ModelMatrix", _tran
      sformStack.getCurrAndGlobal().getMatrix());
                prim->draw("particle");
            
        
        _transformStack.popTransform();
    
    /*---Checking are obstacles enabled or not------*/
    if (_environment->getObstacleEnabled())
    
    (*shader)["3DShading"]->use();
    shader->setShaderParamFromMatrix("3DShading","ViewMatrix",_cam->getModelView(
      ));
        /*--- Drawing the RBD spheres------*/
        _transformStack.pushTransform();
        
            for (int i = 0;i<_rbdSphereList.size();++i)
            
                ngl::Vector _position = _rbdSphereList[i].getCurrentPosition();
                ngl::Real _scale = _rbdSphereList[i].getDrawRadius();
                ngl::Colour _colour = _rbdSphereList[i].getParticleColour();
                _transformStack.getCurrentTransform().setPosition(_position);
                _transformStack.getCurrentTransform().setScale(_scale,_scale,_sca
      le);
                shader->setShaderParam4f("3DShading", "inColor", _colour.m_r,_col
      our.m_g,_colour.m_b,1.0);
                shader->setShaderParamFromMatrix("3DShading","ModelMatrix", _tran
      sformStack.getCurrAndGlobal().getMatrix());
                prim->draw("particle");
            
        
        _transformStack.popTransform();
    
void Render::initialiseRender (EnvironmentAndRigidBody * _environment)
initialises the shaders and member variables of the class required to view the simulation data
Parameters
$\leftarrow$ _environment pointer to EnvironmentAndRigidBody Class
Definition at line 8 of file Render.cpp.
References EnvironmentAndRigidBody::getBBox(), and m_bbox.
    m_bbox = new ngl::BBox(_environment->getBBox()->center(),_environment->
      getBBox()->width(),_environment->getBBox()->height(),_environment->getBBox()->dep
      th());
    ngl::VBOPrimitives *prim = ngl::VBOPrimitives::instance();
    prim->createVBOSphere("particle",1,32);
    ngl::ShaderManager *shader=ngl::ShaderManager::instance();
    shader->createShaderProgram("3DShading");
    shader->attachShader("3DShadingVertex",ngl::VERTEX);
    shader->attachShader("3DShadingFragment",ngl::FRAGMENT);
    shader->loadShaderSource("3DShadingVertex","shaders/Basic.vs");
    shader->loadShaderSource("3DShadingFragment","shaders/Basic.fs");
    shader->compileShader("3DShadingVertex");
    shader->compileShader("3DShadingFragment");
    shader->attachShaderToProgram("3DShading","3DShadingVertex");
    shader->attachShaderToProgram("3DShading","3DShadingFragment");
    shader->bindAttribute("3DShading", 0, "inVertex");
    shader->bindAttribute("3DShading", 1, "perVColor");
    shader->linkProgramObject("3DShading");
    shader->use("3DShading");
    shader->createShaderProgram("ConstantShading");
    shader->attachShader("ConstantShadingVertex",ngl::VERTEX);
    shader->attachShader("ConstantShadingFragment",ngl::FRAGMENT);
    shader->loadShaderSource("ConstantShadingVertex","shaders/Colour.vs");
    shader->loadShaderSource("ConstantShadingFragment","shaders/Colour.fs");
    shader->compileShader("ConstantShadingVertex");
    shader->compileShader("ConstantShadingFragment");
    shader->attachShaderToProgram("ConstantShading","ConstantShadingVertex");
    shader->attachShaderToProgram("ConstantShading","ConstantShadingFragment");
    shader->bindAttribute("ConstantShading", 0, "inVertex");
    shader->bindAttribute("ConstantShading", 1, "perVColor");
    shader->linkProgramObject("ConstantShading");
    shader->use("ConstantShading");
void Render::updateProjection (ngl::Camera * _cam)
updates the projection matrix for the shaders when the glWindow is resized
Parameters
$\leftarrow$ _cam pointer to ngl/Camera Class
Definition at line 131 of file Render.cpp.
    ngl::ShaderManager *shader=ngl::ShaderManager::instance();
    (*shader)["3DShading"]->use();
          shader->setShaderParamFromMatrix("3DShading","projectionMatrix",_cam->g
      etProjection());
    (*shader)["ConstantShading"]->use();
          shader->setShaderParamFromMatrix("ConstantShading","projectionMatrix",_
      cam->getProjection());
Member Data Documentation
ngl::BBox* Render::m_bbox [private]
pointer to ngl/BBox Class
Definition at line 45 of file Render.h.
The documentation for this class was generated from the following files:
include/Render.h
src/Render.cpp