Integrate Class Reference
handles integration to find next position and velocity of particles
#include <Integrate.h>
Public Member Functions
Integrate ()
ctor
void integrateNext (Particle &io_fluidParticle)
integrate next velocity and position of a particle
std::string getIntegrateType () const
get the Integration method
ngl::Real getTimestep () const
get the timestep value
void setTimestep (const ngl::Real _timestep)
set the timestep for the simulation solver
Private Member Functions
void calculateSemiImplicitEuler (Particle &io_fluidParticle)
integrate a particle using semi implicit euler
void calculateLeapfrog (Particle &io_fluidParticle)
integrate a particle using leapfrog
Private Attributes
std::string m_IntegrateType
Integration method.
ngl::Real m_timestep
timestep of simulation
Detailed Description
handles integration to find next position and velocity of particles
Definition at line 17 of file Integrate.h.
Constructor & Destructor Documentation
Integrate::Integrate ()
ctor
Definition at line 7 of file Integrate.cpp.
References SimulationParameters::initialiseIntegrate(), m_IntegrateType, and m_timestep.
    SimulationParameters::initialiseIntegrate(m_IntegrateType,m_timestep);
Member Function Documentation
void Integrate::calculateLeapfrog (Particle & io_fluidParticle) [private]
integrate a particle using leapfrog
Parameters
$\leftrightarrow$ io_fluidParticle the particle that is being affected
Definition at line 35 of file Integrate.cpp.
References Particle::getCurrentAcceleration(), Particle::getCurrentPosition(), Particle::getCurrentVelocity(), Particle::getLastAcceleration(), m_timestep, Particle::updatePosition(), and Particle::updateVelocity().
    /*-----modified leapfrog from http://en.wikipedia.org/wiki/Leapfrog_Integrate
      -----------------------------------------------------------*/
    io_fluidParticle.updateVelocity(io_fluidParticle.getCurrentVelocity() + (((io
      _fluidParticle.getLastAcceleration() + io_fluidParticle.getCurrentAcceleration())
       / 2.0) * m_timestep));
    io_fluidParticle.updatePosition(io_fluidParticle.getCurrentPosition() + (io_f
      luidParticle.getCurrentVelocity() * m_timestep) + ((io_fluidParticle.
      getLastAcceleration() / 2.0) * m_timestep * m_timestep));
void Integrate::calculateSemiImplicitEuler (Particle & io_fluidParticle) [private]
integrate a particle using semi implicit euler
Parameters
$\leftrightarrow$ io_fluidParticle the particle that is being affected
Definition at line 26 of file Integrate.cpp.
References Particle::getCurrentAcceleration(), Particle::getCurrentPosition(), Particle::getCurrentVelocity(), m_timestep, Particle::updatePosition(), and Particle::updateVelocity().
    /*-----semi implicit euler from http://en.wikipedia.org/wiki/Semi-implicit_Eu
      ler----------------------------------------------*/
    io_fluidParticle.updateVelocity(io_fluidParticle.getCurrentVelocity() + (io_f
      luidParticle.getCurrentAcceleration() * m_timestep));
    io_fluidParticle.updatePosition(io_fluidParticle.getCurrentPosition() + (io_f
      luidParticle.getCurrentVelocity() * m_timestep));
std::string Integrate::getIntegrateType () const [inline]
get the Integration method
Definition at line 28 of file Integrate.h.
References m_IntegrateType.
 return m_IntegrateType;
ngl::Real Integrate::getTimestep () const [inline]
get the timestep value
Definition at line 31 of file Integrate.h.
References m_timestep.
 return m_timestep;
void Integrate::integrateNext (Particle & io_fluidParticle)
integrate next velocity and position of a particle
Parameters
$\leftrightarrow$ io_fluidParticle the particle that is being affected
Definition at line 12 of file Integrate.cpp.
References calculateLeapfrog(), calculateSemiImplicitEuler(), and m_IntegrateType.
    /*---Calling chosed integration of the following-----------------------------
      --------*/
    if (m_IntegrateType == "SEMI_IMPLICIT_EULER")
    
        calculateSemiImplicitEuler(io_fluidParticle);
    
    if (m_IntegrateType == "LEAPFROG")
    
        calculateLeapfrog(io_fluidParticle);
    
void Integrate::setTimestep (const ngl::Real _timestep) [inline]
set the timestep for the simulation solver
Parameters
$\leftarrow$ _timestep new timestep
Definition at line 35 of file Integrate.h.
References m_timestep.
 m_timestep = _timestep;
Member Data Documentation
std::string Integrate::m_IntegrateType [private]
Integration method.
Definition at line 40 of file Integrate.h.
ngl::Real Integrate::m_timestep [private]
timestep of simulation
Definition at line 43 of file Integrate.h.
The documentation for this class was generated from the following files:
include/Integrate.h
src/Integrate.cpp