GLWindow Class Reference
management of entities required of simulation and visualization of fluids
#include <GLWindow.h>
Public Member Functions
GLWindow (QWidget *_parent)
ctor
~GLWindow ()
dtor
Protected Member Functions
void initializeGL ()
The following methods must be implimented in the sub class this is called when the window is created.
void resizeGL (const int _w, const int _h)
this is called whenever the window is re-sized
void paintGL ()
this is the main gl drawing routine which is called whenever the window needs to
Private Member Functions
void mouseMoveEvent (QMouseEvent *_event)
this method is called every time a mouse is moved
void mousePressEvent (QMouseEvent *_event)
this method is called everytime the mouse button is pressed inherited from QObject and overridden here.
void mouseReleaseEvent (QMouseEvent *_event)
this method is called everytime the mouse button is released inherited from QObject and overridden here.
void timerEvent (QTimerEvent *_event)
the timer event triggered from the timers
Private Attributes
int m_spinXFace
used to store the x rotation mouse value
int m_spinYFace
used to store the y rotation mouse value
bool m_rotate
flag to indicate if the mouse button is pressed when dragging
int m_origX
the previous x mouse value
int m_origY
the previous y mouse value
int m_FluidTimer
timer check if the iteration process is over
int m_fpsTimer
timer to to calculate frames per second
int m_fps
number iterations performed per second
int m_frames
number iterations performed within one second
float m_elapsedTime
elapsed time after the last simulation data was written
float m_elapsedSimulationTime
elapsed time inside the simulation model
bool m_animate
flag to indicate if animation is active or not
bool m_iterationProcessed
flag to check if a iteration is completed
ngl::Vector m_eye
eye of the camera
ngl::Vector m_look
look/traget of the camera
ngl::Vector m_upVector
up vector for the camera
QTime m_timer
timer to check the iterations performed per second
QTime m_iterationTimer
timer to check the iterations performed per second
bool m_exportEnabled
flag to check exporting of simulation data
std::string m_exportPath
path at which the simulation data is to be written on to the disk
float m_exportFrameInterval
time interval between two frames for writting simulation data
bool m_mouseMove
flag to check if a mouse move event in OpenGL Window has occured
ngl::TransformStack m_transformStack
our transform stack for drawing the teapots
ngl::Camera * m_cam
pointer to ngl/Camera class
SPHSolver * m_sphSolver
pointer to SPHSolver class
EnvironmentAndRigidBody * m_environmentAndRigidBody
pointer to EnviornmentAndRigidBody class
Integrate * m_integrate
pointer to Integrate class
Render * m_render
pointer to Render class
Export * m_export
pointer to Export class
Detailed Description
management of entities required of simulation and visualization of fluids
Definition at line 29 of file GLWindow.h.
Constructor & Destructor Documentation
GLWindow::GLWindow (QWidget * _parent)
ctor
Parameters
$\leftarrow$ _parent the parent window to create the GL context in
Definition at line 20 of file GLWindow.cpp.
References SimulationParameters::initialiseCameraParameters(), SimulationParameters::initialiseExportParameters(), m_animate, m_elapsedSimulationTime, m_elapsedTime, m_environmentAndRigidBody, m_export, m_exportEnabled, m_exportFrameInterval, m_exportPath, m_eye, m_FluidTimer, m_fps, m_fpsTimer, m_frames, m_integrate, m_iterationProcessed, m_iterationTimer, m_look, m_mouseMove, m_render, m_rotate, m_sphSolver, m_timer, and m_upVector.
                    :
                    QGLWidget(_parent)
    SimulationParameters::initialiseCameraParameters(m_eye,m_look,m_upVector);
    SimulationParameters::initialiseExportParameters(m_exportEnabled,
      m_exportPath,m_exportFrameInterval);
    // set this widget to have the initial keyboard focus
    setFocus();
    // re-size the widget to that of the parent (in this case the GLFrame passed
      in on construction)
    this->resize(_parent->size());
    m_rotate=true;
    m_FluidTimer = startTimer(0);
    m_fpsTimer =startTimer(0);
    m_fps=0;
    m_frames=0;
    m_elapsedSimulationTime = 0.0;
    m_elapsedTime = 0.0;
    m_timer.start();
    m_iterationTimer.start();
    m_animate = true;
    m_iterationProcessed = false;
    m_mouseMove = false;
    //create the integration
    m_integrate = new Integrate();
    //create the environment
    m_environmentAndRigidBody = new EnvironmentAndRigidBody();
    //create the fluid solver
    m_sphSolver = new SPHSolver();
    m_render = new Render();
    if (m_exportEnabled)
    
        m_export = new Export(m_exportPath);
    
GLWindow::~GLWindow ()
dtor
Definition at line 252 of file GLWindow.cpp.
References m_environmentAndRigidBody, m_integrate, and m_sphSolver.
    delete m_sphSolver;
    delete m_environmentAndRigidBody;
    delete m_integrate;
Member Function Documentation
void GLWindow::initializeGL () [protected]
The following methods must be implimented in the sub class this is called when the window is created.
Definition at line 71 of file GLWindow.cpp.
References Render::initialiseRender(), m_cam, m_environmentAndRigidBody, m_eye, m_look, m_render, and m_upVector.
  glClearColor(0.4f, 0.4f, 0.4f, 1.0f); // Grey Background
  // enable depth testing for drawing
  glEnable(GL_DEPTH_TEST);
   // Now we will create a basic Camera from the graphics library
   // This is a static camera so it only needs to be set once
   // First create Values for the camera position
   ngl::NGLInit *Init = ngl::NGLInit::instance();
   Init->initGlew();
   m_cam= new ngl::Camera(m_eye,m_look,m_upVector,ngl::PERSPECTIVE);
   // set the shape using FOV 45 Aspect Ratio based on Width and Height
   // The final two are near and far clipping planes of 0.5 and 10
   m_cam->setShape(50,1.0,0.5,150,ngl::PERSPECTIVE);
   m_render->initialiseRender(m_environmentAndRigidBody);
   glEnable(GL_DEPTH_TEST); // for removal of hidden surfaces
void GLWindow::mouseMoveEvent (QMouseEvent * _event) [private]
this method is called every time a mouse is moved
Parameters
_event the Qt Event structure
Definition at line 162 of file GLWindow.cpp.
References m_mouseMove, m_origX, m_origY, m_rotate, m_spinXFace, and m_spinYFace.
  // note the method buttons() is the button state when event was called
  // this is different from button() which is used to check which button was
  // pressed when the mousePress/Release event is generated
  if(m_rotate && _event->buttons() == Qt::LeftButton)
  
    m_spinYFace = (m_spinYFace + (_event->x() - m_origX)) % 360 ;
    m_spinXFace = (m_spinXFace + (_event->y() - m_origY)) % 360 ;
    m_origX = _event->x();
    m_origY = _event->y();
  
  // re-draw GL
  m_mouseMove = true;
  updateGL();
  m_mouseMove = false;
void GLWindow::mousePressEvent (QMouseEvent * _event) [private]
this method is called everytime the mouse button is pressed inherited from QObject and overridden here.
Parameters
_event the Qt Event structure
Definition at line 182 of file GLWindow.cpp.
References m_origX, m_origY, and m_rotate.
  // this method is called when the mouse button is pressed in this case we
  // store the value where the maouse was clicked (x,y) and set the Rotate flag t
      o true
  if(_event->button() == Qt::LeftButton)
  
    m_origX = _event->x();
    m_origY = _event->y();
    m_rotate =true;
  
void GLWindow::mouseReleaseEvent (QMouseEvent * _event) [private]
this method is called everytime the mouse button is released inherited from QObject and overridden here.
Parameters
_event the Qt Event structure
Definition at line 197 of file GLWindow.cpp.
References m_rotate.
  // this event is called when the mouse button is released
  // we then set Rotate to false
  if (_event->button() == Qt::LeftButton)
  
    m_rotate=false;
  
void GLWindow::paintGL () [protected]
this is the main gl drawing routine which is called whenever the window needs to
Definition at line 110 of file GLWindow.cpp.
References Render::draw(), SPHSolver::getFluidParticleList(), Integrate::getIntegrateType(), Integrate::getTimestep(), m_cam, m_elapsedSimulationTime, m_environmentAndRigidBody, m_fps, m_integrate, m_iterationProcessed, m_iterationTimer, m_mouseMove, m_render, m_sphSolver, m_spinXFace, m_spinYFace, and m_transformStack.
    // clear the screen and depth buffer
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
   // build our transform stack
    ngl::Transformation trans;
    // set the mouse rotation
    trans.setRotation(m_spinXFace,m_spinYFace,0);
    // set this in the TX stack
    m_transformStack.setGlobal(trans);
    m_render->draw(m_environmentAndRigidBody,m_sphSolver,m_transformStack,m_cam);
      
    if (m_mouseMove == false)
    
        m_iterationProcessed = true;
    
    glUseProgramObjectARB(0);
    QFont font;
    font.setBold(true);
    font.setPointSize(10);
    glColor3f(0.7,0.7,0.7);
    QString text =QString("Total number of fluid particles : %1").arg(
      m_sphSolver->getFluidParticleList().size());
    renderText(500,20,text,font);
    text =QString("Integration Method used : %1").arg(m_integrate->
      getIntegrateType().c_str());
    renderText(500,40,text,font);
    text =QString("Timestep value : %1").arg(m_integrate->getTimestep());
    renderText(500,60,text,font);
    text =QString("Iterations performed per second : %1").arg(m_fps);
    renderText(15,20,text,font);
    text =QString("Elapsed time inside the simulation model : %1 seconds").arg(f
      loor(m_elapsedSimulationTime));
    renderText(15,40,text,font);
    float tmp = m_iterationTimer.elapsed();
    tmp = tmp / 1000;
    tmp = tmp * 100;
    tmp = floor(tmp);
    tmp = tmp / 100;
    text =QString("Time taken to process a single Iteration : %1 seconds").arg(t
      mp);
    renderText(15,60,text,font);
    m_iterationTimer.restart();
void GLWindow::resizeGL (const int _w, const int _h) [protected]
this is called whenever the window is re-sized
Parameters
$\leftarrow$ _w the width of the resized window
$\leftarrow$ _h the height of the resized window
Definition at line 97 of file GLWindow.cpp.
References m_cam, m_render, and Render::updateProjection().
  glViewport(0,0,_w,_h);
  m_cam->setShape(45,(float)_w/_h,0.001,500,ngl::PERSPECTIVE);
  m_render->updateProjection(m_cam);
void GLWindow::timerEvent (QTimerEvent * _event) [private]
the timer event triggered from the timers
Parameters
_event the event of the timer triggered by Qt
Definition at line 209 of file GLWindow.cpp.
References Export::exportDataOut(), SPHSolver::getFluidNameList(), SPHSolver::getFluidParticlePositionList(), Integrate::getTimestep(), m_animate, m_elapsedSimulationTime, m_elapsedTime, m_environmentAndRigidBody, m_export, m_exportEnabled, m_exportFrameInterval, m_FluidTimer, m_fps, m_fpsTimer, m_frames, m_integrate, m_iterationProcessed, m_sphSolver, m_timer, and SPHSolver::updateFluid().
        if(_event->timerId() == m_FluidTimer)
        
                if (m_animate ==true)
                
                    if(m_iterationProcessed)
                    
                        m_iterationProcessed = false;
                        m_elapsedTime = m_elapsedTime + m_integrate->getTimestep(
      );
                        m_elapsedSimulationTime += m_integrate->getTimestep();
                        ++m_frames;
                        m_sphSolver->updateFluid(m_environmentAndRigidBody,
      m_integrate);
                        if (m_exportEnabled)
                        
                            if (m_elapsedTime >= m_exportFrameInterval)
                            
                            m_export->exportDataOut(m_sphSolver->
      getFluidNameList(),m_sphSolver->getFluidParticlePositionList(),
      m_environmentAndRigidBody);
                            m_elapsedTime = 0;
                            
                        
                        updateGL();
                        return;
                    
                
        
        if(_event->timerId() == m_fpsTimer)
          
            if(m_timer.elapsed() > 1000.0)
            
              m_fps=m_frames;
              m_frames=0;
              m_timer.restart();
            
           
Member Data Documentation
bool GLWindow::m_animate [private]
flag to indicate if animation is active or not
Definition at line 125 of file GLWindow.h.
ngl::Camera* GLWindow::m_cam [private]
pointer to ngl/Camera class
Definition at line 161 of file GLWindow.h.
float GLWindow::m_elapsedSimulationTime [private]
elapsed time inside the simulation model
Definition at line 122 of file GLWindow.h.
float GLWindow::m_elapsedTime [private]
elapsed time after the last simulation data was written
Definition at line 119 of file GLWindow.h.
EnvironmentAndRigidBody* GLWindow::m_environmentAndRigidBody [private]
pointer to EnviornmentAndRigidBody class
Definition at line 167 of file GLWindow.h.
Export* GLWindow::m_export [private]
pointer to Export class
Definition at line 176 of file GLWindow.h.
bool GLWindow::m_exportEnabled [private]
flag to check exporting of simulation data
Definition at line 146 of file GLWindow.h.
float GLWindow::m_exportFrameInterval [private]
time interval between two frames for writting simulation data
Definition at line 152 of file GLWindow.h.
std::string GLWindow::m_exportPath [private]
path at which the simulation data is to be written on to the disk
Definition at line 149 of file GLWindow.h.
ngl::Vector GLWindow::m_eye [private]
eye of the camera
Definition at line 131 of file GLWindow.h.
int GLWindow::m_FluidTimer [private]
timer check if the iteration process is over
Definition at line 107 of file GLWindow.h.
int GLWindow::m_fps [private]
number iterations performed per second
Definition at line 113 of file GLWindow.h.
int GLWindow::m_fpsTimer [private]
timer to to calculate frames per second
Definition at line 110 of file GLWindow.h.
int GLWindow::m_frames [private]
number iterations performed within one second
Definition at line 116 of file GLWindow.h.
Integrate* GLWindow::m_integrate [private]
pointer to Integrate class
Definition at line 170 of file GLWindow.h.
bool GLWindow::m_iterationProcessed [private]
flag to check if a iteration is completed
Definition at line 128 of file GLWindow.h.
QTime GLWindow::m_iterationTimer [private]
timer to check the iterations performed per second
Definition at line 143 of file GLWindow.h.
ngl::Vector GLWindow::m_look [private]
look/traget of the camera
Definition at line 134 of file GLWindow.h.
bool GLWindow::m_mouseMove [private]
flag to check if a mouse move event in OpenGL Window has occured
Definition at line 155 of file GLWindow.h.
int GLWindow::m_origX [private]
the previous x mouse value
Definition at line 101 of file GLWindow.h.
int GLWindow::m_origY [private]
the previous y mouse value
Definition at line 104 of file GLWindow.h.
Render* GLWindow::m_render [private]
pointer to Render class
Definition at line 173 of file GLWindow.h.
bool GLWindow::m_rotate [private]
flag to indicate if the mouse button is pressed when dragging
Definition at line 98 of file GLWindow.h.
SPHSolver* GLWindow::m_sphSolver [private]
pointer to SPHSolver class
Definition at line 164 of file GLWindow.h.
int GLWindow::m_spinXFace [private]
used to store the x rotation mouse value
Definition at line 92 of file GLWindow.h.
int GLWindow::m_spinYFace [private]
used to store the y rotation mouse value
Definition at line 95 of file GLWindow.h.
QTime GLWindow::m_timer [private]
timer to check the iterations performed per second
Definition at line 140 of file GLWindow.h.
ngl::TransformStack GLWindow::m_transformStack [private]
our transform stack for drawing the teapots
Definition at line 158 of file GLWindow.h.
ngl::Vector GLWindow::m_upVector [private]
up vector for the camera
Definition at line 137 of file GLWindow.h.
The documentation for this class was generated from the following files:
include/GLWindow.h
src/GLWindow.cpp