SpatialHashing Class Reference
implements spatial hashing for the search of fluid particle neighbours
#include <SpatialHashing.h>
Public Member Functions
SpatialHashing (const int _numberOfFluidParticles, const float _smoothingLength)
ctor
~SpatialHashing ()
dtor
void initialiseSpatialHashing (const int _numberOfFluidParticles, const float _smoothingLength)
initialiseSpatialHashing the spatial structure
void refreshHashmap (std::vector< FluidParticle > &_particleList)
refresh the hash map at each iteration
void clearHashmap ()
clear the hash map
std::vector< FluidParticle > searchFluidParticleNeighbours (const ngl::Vector _centerPosition)
return neighbours of a particle
void setCellSize (const ngl::Real _size)
set the cell size of the spatial structure
Private Member Functions
int modulus (const int _a, const int _b)
calculate the modulus of 2 numbers
int getNextPrimeNumber (const int _start)
return the next prime number
std::vector< int > discretizingVector (const ngl::Vector _position)
discretise an array of vectors into an array of integers
int hashPosition (const ngl::Vector _position)
hash a position to a hash key
void getNeighbouringCells (const ngl::Vector _centerPosition, const bool _checkNeighboursAreInSmoothingLength, std::vector< FluidParticle > &o_neighbourList)
determine neighbours of a fluid particle, given its position
bool inListCheck (const int _testId, std::vector< FluidParticle > &_neighbourList)
check if a neighbour is a duplicate
Private Attributes
hashmap m_hashMap
the spatial hash map
float m_cellSize
the cell size used for spatial calculations
int m_mapSize
the map size
int m_firstLargePrimeNumber
large prime number 1
int m_secondLargePrimeNumber
large prime number 2
int m_thirdLargePrimeNumber
large prime number 3
int m_initialNeighbourListSize
reserved space size for neighbours
Detailed Description
implements spatial hashing for the search of fluid particle neighbours
Definition at line 21 of file SpatialHashing.h.
Constructor & Destructor Documentation
SpatialHashing::SpatialHashing (const int _numberOfFluidParticles, const float _smoothingLength)
ctor
Parameters
$\leftarrow$ _numberOfFluidParticles the fluid particle count
$\leftarrow$ _smoothingLength the smoothing length
Definition at line 10 of file SpatialHashing.cpp.
    //initialise large prime numbers
    m_firstLargePrimeNumber = 73856093;
    m_secondLargePrimeNumber = 19349663;
    m_thirdLargePrimeNumber = 83492791;
    //initialise neighbour list
    m_initialNeighbourListSize = 50;
    //initialise hash params
    initialiseSpatialHashing(_numberOfFluidParticles, _smoothingLength);
SpatialHashing::~SpatialHashing ()
dtor
Definition at line 27 of file SpatialHashing.cpp.
    //clean up
    std::cout << "Neighbour Cleanup" << std::endl;
Member Function Documentation
void SpatialHashing::clearHashmap ()
clear the hash map
Definition at line 162 of file SpatialHashing.cpp.
References m_hashMap.
    //clears hashmap
    m_hashMap.clear();
std::vector< int > SpatialHashing::discretizingVector (const ngl::Vector _position) [private]
discretise an array of vectors into an array of integers
Parameters
$\leftarrow$ _position the vector position to discretize
Definition at line 124 of file SpatialHashing.cpp.
References m_cellSize.
    std::vector<int> pos;
    pos.reserve(3);
    pos.push_back(floor(_position.m_x / m_cellSize));
    pos.push_back(floor(_position.m_y / m_cellSize));
    pos.push_back(floor(_position.m_z / m_cellSize));
    return pos;
void SpatialHashing::getNeighbouringCells (const ngl::Vector _centerPosition, const bool _checkNeighboursAreInSmoothingLength, std::vector< FluidParticle > & o_neighbourList) [private]
determine neighbours of a fluid particle, given its position
Parameters
$\leftarrow$ _centerPosition the position of the fluid particle
$\leftarrow$ _checkNeighboursAreInSmoothingLength flag to determine whether only neighbours within the smoothing length are added
$\rightarrow$ o_neighbourList stores the list neighbours
Definition at line 191 of file SpatialHashing.cpp.
References Particle::getCurrentPosition(), and Particle::getId().
    //hash position
    int hashKey = hashPosition(_centerPosition);
    //get particles of cell[hashkey] from hash map
    std::pair<hashmap::iterator, hashmap::iterator> neighbourCandidateList =
      m_hashMap.equal_range(hashKey);
    //loop over neighbour list
    for (hashmap::iterator candidate = neighbourCandidateList.first; candidate !=
       neighbourCandidateList.second; candidate++)
    
        //get neighbour particle
        FluidParticle neighbourCandidate = (*candidate).second;
        //consider only non-duplicate candidates
        if (!inListCheck(neighbourCandidate.getId(), o_neighbourList))
        
            //assume neighbour is valid
            bool isValidToAdd = true;
            //filter only neighbours within smoothing length if check is enabled
            if (_checkNeighboursAreInSmoothingLength)
            
                //get separation distance between centerposition and neighbour po
      sition
                ngl::Real distance = (_centerPosition - neighbourCandidate.
      getCurrentPosition()).length();
                //check if distance is within smoothing length (cell size)
                if (distance > m_cellSize) isValidToAdd = false;
            
            //add neighbour particle to neighbour list if valid
            if (isValidToAdd) o_neighbourList.push_back(neighbourCandidate);
        
    
int SpatialHashing::getNextPrimeNumber (const int _start) [private]
return the next prime number
Parameters
$\leftarrow$ _start the start number from which to find the next prime number
Definition at line 59 of file SpatialHashing.cpp.
    int i = _start;
    bool isPrimeNumberFound = true;
    bool isNextPrimeNumberFound = false;
    //Get Square root of number and iterate, start from 2
    int check = (int)sqrt((double)i);
    for (int j = 2; j <= check; j++)
    
        if (i % j == 0)
        
            isPrimeNumberFound = false;
            break;
        
    
    if (isPrimeNumberFound)
    
        //i itself is the next prime number
        return i;
    
    else
    
        //i is not a prime number -> must search next one
        i++;
        isPrimeNumberFound = true;
        // Increment current number to find next prime number
        while (isNextPrimeNumberFound == false)
        
            check = (int)sqrt((double)(i));
            for (int j = 2; j <= check; j++)
            
                if (i % j == 0)
                
                    isPrimeNumberFound = false;
                    break;
                
            
            if (isPrimeNumberFound)
                isNextPrimeNumberFound = true;
            else
            
                i++;
                isPrimeNumberFound = true;
            
        
        if (isNextPrimeNumberFound)
        
            //i is the next prime number
            return i;
        
    
    //eventually, nothing found?
    return _start;
int SpatialHashing::hashPosition (const ngl::Vector _position) [private]
hash a position to a hash key
Parameters
$\leftarrow$ _position the position to hash
Definition at line 136 of file SpatialHashing.cpp.
References discretizingVector(), m_firstLargePrimeNumber, m_mapSize, m_secondLargePrimeNumber, m_thirdLargePrimeNumber, and modulus().
    //discretizingVector position to array of int
    std::vector<int> discretePosition = discretizingVector(_position);
    //calculate hash key
    int key = modulus((discretePosition[0] * m_firstLargePrimeNumber) ^ (discrete
      Position[1] * m_secondLargePrimeNumber) ^ (discretePosition[2] *
      m_thirdLargePrimeNumber), m_mapSize);
    return key;
void SpatialHashing::initialiseSpatialHashing (const int _numberOfFluidParticles, const float _smoothingLength)
initialiseSpatialHashing the spatial structure
Parameters
$\leftarrow$ _numberOfFluidParticles the fluid particle count
$\leftarrow$ _smoothingLength the smoothing length
Definition at line 34 of file SpatialHashing.cpp.
    //initialise cell size
    m_cellSize = _smoothingLength;
    //initialise hash map size
    m_mapSize = getNextPrimeNumber(2 * _numberOfFluidParticles);
bool SpatialHashing::inListCheck (const int _testId, std::vector< FluidParticle > & _neighbourList) [private]
check if a neighbour is a duplicate
Parameters
$\leftarrow$ _testId the id of the neighbour to check in the list
$\leftarrow$ _neighbourList the list of neighbour that will be used for the duplicate check
Definition at line 169 of file SpatialHashing.cpp.
    //assume not found
    bool found = false;
    //loop through the temporary neighbour list
    for (int i = 0; i < _neighbourList.size(); i++)
    
        if (_neighbourList[i].getId() == _testId)
        
            found = true;
            break;
        
    
    return found;
int SpatialHashing::modulus (const int _a, const int _b) [private]
calculate the modulus of 2 numbers
Parameters
$\leftarrow$ _a the first number
$\leftarrow$ _b the second number
Definition at line 46 of file SpatialHashing.cpp.
    //perform huge integer modulus
    //issue of negative modulus : http://mathforum.org/library/drmath/view/52343.
      html
    //solved at stackoverflow : http://stackoverflow.com/questions/1082917/mod-of
      -negative-number-is-melting-my-brain
    //adapted from StackOverflow
    int modulus = _a % _b;
    return modulus < 0 ? modulus + _b : modulus;
void SpatialHashing::refreshHashmap (std::vector< FluidParticle > & _particleList)
refresh the hash map at each iteration
Parameters
$\leftarrow$ _particleList the fluid particles
Definition at line 147 of file SpatialHashing.cpp.
References hashPosition(), and m_hashMap.
#pragma omp for schedule(dynamic, 50)
    //loop through each particle in the fluid
    for (int i = 0; i < _particleList.size(); ++i)
    
        //hash position
        int hashKey = hashPosition(_particleList[i].getCurrentPosition());
#pragma omp critical
        //add (hashkey, particle) pair to hashmap
        m_hashMap.insert(std::pair<int, FluidParticle>(hashKey, _particleList[i])
      );
    
std::vector< FluidParticle > SpatialHashing::searchFluidParticleNeighbours (const ngl::Vector _centerPosition)
return neighbours of a particle
Parameters
$\leftarrow$ _centerPosition the particle's position
Definition at line 231 of file SpatialHashing.cpp.
References discretizingVector(), getNeighbouringCells(), and m_cellSize.
    //initialise temp neighbour lists
    std::vector<FluidParticle> neighbourList;
    //neighbourList.reserve(m_initialNeighbourListSize);
    std::vector<FluidParticle> neighbourTempList;
    //neighbourTempList.reserve(m_initialNeighbourListSize);
    //first, get neighbours @ centerposition
    getNeighbouringCells(_centerPosition, false, neighbourTempList);
    //then, get neighbours from bounding box [centerPos - cellSize, centerPos + c
      ellSize]
    ngl::Vector limit(m_cellSize, m_cellSize, m_cellSize);
    std::vector<int> discreteMinBounds = discretizingVector(_centerPosition - lim
      it);
    std::vector<int> discreteMaxBounds = discretizingVector(_centerPosition + lim
      it);
    //loop from minBound to maxBound and find neighbours in hashmap
    ngl::Real sampleStep = 0.85;
    for (ngl::Real x = discreteMinBounds[0]; x < discreteMaxBounds[0]; x += sampl
      eStep)
    
        for (ngl::Real y = discreteMinBounds[1]; y < discreteMaxBounds[1]; y += s
      ampleStep)
        
            for (ngl::Real z = discreteMinBounds[2]; z < discreteMaxBounds[2]; z
      += sampleStep)
            
                //fill in neighbour list with neighbours @ test position(x,y,z)
                getNeighbouringCells(ngl::Vector(x, y, z), true, neighbourTempLis
      t);
            
        
    
    //do a final distance check to ensure neighbours are within smoothing length
    for (int i = 0; i < neighbourTempList.size(); ++i)
    
        //get separation distance between centerposition and neighbour position
        ngl::Real distance = (_centerPosition - neighbourTempList[i].getCurrentPo
      sition()).length();
        //add to final list only if distance is within smoothing length (cell siz
      e)
        if (distance < m_cellSize) neighbourList.push_back(neighbourTempList[i]);
      
    
    //return final list
    return neighbourList;
void SpatialHashing::setCellSize (const ngl::Real _size) [inline]
set the cell size of the spatial structure
Parameters
$\leftarrow$ _size the new cell size
Definition at line 58 of file SpatialHashing.h.
References m_cellSize.
 m_cellSize = _size;
Member Data Documentation
float SpatialHashing::m_cellSize [private]
the cell size used for spatial calculations
Definition at line 66 of file SpatialHashing.h.
int SpatialHashing::m_firstLargePrimeNumber [private]
large prime number 1
Definition at line 72 of file SpatialHashing.h.
hashmap SpatialHashing::m_hashMap [private]
the spatial hash map
Definition at line 63 of file SpatialHashing.h.
int SpatialHashing::m_initialNeighbourListSize [private]
reserved space size for neighbours
Definition at line 81 of file SpatialHashing.h.
int SpatialHashing::m_mapSize [private]
the map size
Definition at line 69 of file SpatialHashing.h.
int SpatialHashing::m_secondLargePrimeNumber [private]
large prime number 2
Definition at line 75 of file SpatialHashing.h.
int SpatialHashing::m_thirdLargePrimeNumber [private]
large prime number 3
Definition at line 78 of file SpatialHashing.h.
The documentation for this class was generated from the following files:
include/SpatialHashing.h
src/SpatialHashing.cpp