SimulationParameters Class Reference
reads the values from the XML file and intialises the fluid solver
#include <SimulationParameters.h>
Static Public Member Functions
static void initialiseSPHFluidSolver (ngl::Real &o_smoothingLength, std::vector< FluidParticle > &o_fluidParticleList, std::string &o_visualizationType, bool &o_drawFluidParticles, std::vector< std::string > &o_fluidNameList)
initialise solver
static void initialiseEnvironment (bool &o_rbdCollsionEnabled, ngl::Vector &o_boundaryPosition, ngl::Vector &o_boundaryDimension, ngl::Real &o_boundaryRestitutionCoefficientForFluid, std::vector< Particle > &o_rbdSphereList, ngl::Real &o_rbdSphereRestitutionCoefficient, ngl::Colour &o_boundaryColour)
initialise environment
static void initialiseIntegrate (std::string &o_IntegrateType, ngl::Real &o_timeStep)
initialise Integrate
static void initialiseCameraParameters (ngl::Vector &o_eye, ngl::Vector &o_look, ngl::Vector &o_up)
initialise Camera
static void initialiseExportParameters (bool &o_exportEnabled, std::string &o_exportPath, float &o_exportFrameInterval)
initialise the parameter required to export simulation data out to disk
Static Public Attributes
static bool s_debug = true
debug parameter used in all the files to enable debugging and console output
static ngl::Real s_accelerationOfFreeFall = -9.28
acceleration due to gravity(free fall) value
static ngl::Real s_gravityAcceleration
acceleration due to gravity(free fall) value
static ngl::Colour s_boundaryColour
colour of the boundry box
static int s_nextFluidParticleId = 0
global unique id available for creation of next particle in a fluid
static int s_nextRBDSphereId = -1
global unique id available for creation of next passive sphere rigid body
Static Private Member Functions
static std::vector< ngl::Real > getFloatVectorFromString (const std::string _str, const int _d)
utility function to split a string into a vector of floats
Static Private Attributes
static std::string s_settingsDocumentPath = `SolverParameters/Settings.xml`
the path of the configuration xml file
Detailed Description
reads the values from the XML file and intialises the fluid solver
Definition at line 20 of file SimulationParameters.h.
Member Function Documentation
std::vector< ngl::Real > SimulationParameters::getFloatVectorFromString (const std::string _str, const int _d) [static, private]
utility function to split a string into a vector of floats
Parameters
$\leftarrow$ _str the input string to be split
$\leftarrow$ _d the count of split parts to be used as the size of the vector
Definition at line 21 of file SimulationParameters.cpp.
    //split string into array of strings by ","
    std::vector<std::string> strArray;
    boost::split(strArray, _str, boost::is_any_of(","));
    //loop through strings and convert to float array
    std::vector<ngl::Real> floatArray;
    for (int i = 0; i < _d; i++) floatArray.push_back(boost::lexical_cast<ngl::Re
      al>(strArray[i]));
    //return array of float
    return floatArray;
void SimulationParameters::initialiseCameraParameters (ngl::Vector & o_eye, ngl::Vector & o_look, ngl::Vector & o_up) [static]
initialise Camera
Parameters
$\rightarrow$ o_eye eye for the Camera
$\rightarrow$ o_look look/target for the Camera
$\rightarrow$ o_up up vector for the Camera
Definition at line 245 of file SimulationParameters.cpp.
References getFloatVectorFromString(), and s_settingsDocumentPath.
    //load settings xml file
    pugi::xml_document doc;
    doc.load_file(s_settingsDocumentPath.c_str());
    //load global settings here
    pugi::xpath_node_set node = doc.select_nodes("/Settings/Camera");
    std::vector<ngl::Real> tmp;
    tmp = getFloatVectorFromString(node.first().node().attribute("eye").value(),
      3);
    o_eye.set(tmp[0],tmp[1],tmp[2]);
    tmp = getFloatVectorFromString(node.first().node().attribute("look").value(),
       3);
    o_look.set(tmp[0],tmp[1],tmp[2]);
    tmp = getFloatVectorFromString(node.first().node().attribute("up").value(), 3
      );
    o_up.set(tmp[0],tmp[1],tmp[2]);
    std::cout << "Camera Values ---------" << ":: " << o_eye << "
      :: " << o_look << "Vector :: " << o_up << std::endl;
void SimulationParameters::initialiseEnvironment (bool & o_rbdCollsionEnabled, ngl::Vector & o_boundaryPosition, ngl::Vector & o_boundaryDimension, ngl::Real & o_boundaryRestitutionCoefficientForFluid, std::vector< Particle > & o_rbdSphereList, ngl::Real & o_rbdSphereRestitutionCoefficient, ngl::Colour & o_boundaryColour) [static]
initialise environment
Parameters
$\rightarrow$ o_rbdCollsionEnabled flag to toggle rbd
$\rightarrow$ o_boundaryPosition boundary position
$\rightarrow$ o_boundaryDimension boundary size
$\rightarrow$ o_boundaryRestitutionCoefficientForFluid boundary-fluid restitution
$\rightarrow$ o_rbdSphereList list of sphere rbd
$\rightarrow$ o_rbdSphereRestitutionCoefficient rbd-fluid restitution
$\rightarrow$ o_boundaryColour colour of the boundry to be displayed
Definition at line 38 of file SimulationParameters.cpp.
References getFloatVectorFromString(), s_nextRBDSphereId, and s_settingsDocumentPath.
    /*----Load Settings from XML File--------------------------------------------
      --*/
    pugi::xml_document doc;
    doc.load_file(s_settingsDocumentPath.c_str());
    //temporary variable
    std::vector<ngl::Real> tmp;
    pugi::xpath_node_set node = doc.select_nodes("/Settings/Environment");
    /*--- Reading Boundry Parameters-------------------------------------------*/
      
    tmp = getFloatVectorFromString(node.first().node().select_single_node("Bounda
      ry").node().attribute("position").value(), 3);
    o_boundaryPosition.set(tmp[0], tmp[1], tmp[2]);
    tmp = getFloatVectorFromString(node.first().node().select_single_node("Bounda
      ry").node().attribute("dimension").value(), 3);
    o_boundaryDimension.set(tmp[0], tmp[1], tmp[2]);
    o_boundaryRestitutionCoefficientForFluid = node.first().node().select_single_
      node("Boundary").node().attribute("restitutionForFluid").as_float();
    tmp = getFloatVectorFromString(node.first().node().select_single_node("Bounda
      ry").node().attribute("colour").value(), 3);
    o_boundaryColour.set(tmp[0],tmp[1],tmp[2],1.0);
    /*--- Read CollisionParameters-----------------------------------------------
      --------------------*/
    node = doc.select_nodes("/Settings/Environment/Obstacles");
    o_rbdCollsionEnabled = node.first().node().attribute("enabled").as_bool();
    o_rbdSphereRestitutionCoefficient = node.first().node().attribute("restitutio
      n").as_float();
    /*---- Creating and Storing Rigid Body Sphere -------------------------------
      ----------*/
    node = node.first().node().select_nodes("Sphere");
    for (pugi::xpath_node_set::const_iterator it = node.begin(); it != node.end()
      ; ++it)
    
        //get details for an obstacle
        pugi::xpath_node node1 = *it;
        //get parameters active parameter
        tmp = getFloatVectorFromString(node1.node().attribute("position").value()
      , 3);
        ngl::Vector position(tmp[0], tmp[1], tmp[2]);
        ngl::Vector velocity(0,0,0);
        ngl::Real collisionRadius = node1.node().attribute("collisionRadius").as_
      float();
        ngl::Real drawRadius = node1.node().attribute("drawRadius").as_float();
        tmp = getFloatVectorFromString(node1.node().attribute("colour").value(),
      3);
        ngl::Colour colour(tmp[0], tmp[1], tmp[2]);
        /*---Create and Add Spheres to RBDSphere List----------------------------
      ------------------------*/
        Particle p = Particle (SimulationParameters::s_nextRBDSphereId--,0,positi
      on,colour,collisionRadius,drawRadius,velocity);
        o_rbdSphereList.push_back(p);
    
void SimulationParameters::initialiseExportParameters (bool & o_exportEnabled, std::string & o_exportPath, float & o_exportFrameInterval) [static]
initialise the parameter required to export simulation data out to disk
Parameters
$\rightarrow$ o_exportEnabled flag to check exporting of simulation data
$\rightarrow$ o_exportPath path, where the simulation data is to be exported
$\rightarrow$ o_exportFrameInterval frame interval value at which the simulation data is to be exported
Definition at line 273 of file SimulationParameters.cpp.
References s_settingsDocumentPath.
    //load settings xml file
    pugi::xml_document doc;
    doc.load_file(s_settingsDocumentPath.c_str());
    //load global settings here
    pugi::xpath_node_set node = doc.select_nodes("/Settings/Export");
    o_exportEnabled = node.first().node().attribute("enable").as_bool();
    o_exportPath = node.first().node().attribute("path").value();
    int i = node.first().node().attribute("exportFPS").as_int();
    float temp = (1.0 / i) * 100;
    temp = floor(temp);
    temp = temp / 100.0 ;
    o_exportFrameInterval = temp ;
    std::cout << "o_exportFrameINterval :: " << o_exportFrameInterval << std::end
      l;
void SimulationParameters::initialiseIntegrate (std::string & o_IntegrateType, ngl::Real & o_timeStep) [static]
initialise Integrate
Parameters
$\rightarrow$ o_IntegrateType method to use for integration
$\rightarrow$ o_timeStep timestep value for integration
Definition at line 225 of file SimulationParameters.cpp.
References s_settingsDocumentPath.
    //load settings xml file
    pugi::xml_document doc;
    doc.load_file(s_settingsDocumentPath.c_str());
    //load global settings here
    pugi::xpath_node_set node = doc.select_nodes("/Settings/Integration");
    o_IntegrateType = node.first().node().attribute("type").value();
    o_timeStep = node.first().node().attribute("timestep").as_float();
    std::cout << "Integration Type :: " << o_IntegrateType << "Time Step
       Value :: " << o_timeStep << std::endl;
    std::cout << "" << std::endl;
void SimulationParameters::initialiseSPHFluidSolver (ngl::Real & o_smoothingLength, std::vector< FluidParticle > & o_fluidParticleList, std::string & o_visualizationType, bool & o_drawFluidParticles, std::vector< std::string > & o_fluidNameList) [static]
initialise solver
Parameters
$\rightarrow$ o_smoothingLength smoothing length of neighbour structure
$\rightarrow$ o_fluidParticleList fluid particle list
$\rightarrow$ o_visualizationType shader to be used while displaying simulation data realtime
$\rightarrow$ o_drawFluidParticles flag to check rendering of fluid particle
$\rightarrow$ o_fluidNameList name list of diffierent fluids created
Definition at line 108 of file SimulationParameters.cpp.
References getFloatVectorFromString(), s_nextFluidParticleId, and s_settingsDocumentPath.
    //load settings xml file
    pugi::xml_document doc;
    doc.load_file(s_settingsDocumentPath.c_str());
    //load global settings here
    pugi::xpath_node_set node = doc.select_nodes("/Settings/FluidSolver");
    //read smoothing length
    o_smoothingLength = node.first().node().attribute("smoothingLength").as_float
      ();
    //initially reserve space for maximum growth of particle list
    int initialReservedParticleCount =node.first().node().attribute("initialReser
      vedParticleCount").as_int();
    o_fluidParticleList.reserve(initialReservedParticleCount);
    o_visualizationType = node.first().node().attribute("visualization").value();
      
    o_drawFluidParticles = node.first().node().attribute("enableVisulization").as
      _bool();
    std::cout << "Particle Hydrodynamics Solver" << std::endl;
    std::cout << "Smoothing Length :: " << o_smoothingLength << "Visualiz
      ation Shading Type :: " << o_visualizationType << "" << std::endl;
    //tmp variable
    std::vector<ngl::Real> tmp;
    /*------Getting List of Fluids-------------------------------*/
    node = doc.select_nodes("/Settings/FluidSolver/Fluid");
    for (pugi::xpath_node_set::const_iterator it = node.begin(); it != node.end()
      ; ++it)
    
        //get details for a fluid
        pugi::xpath_node node = *it;
        //get its active parameter
        bool isActive = node.node().attribute("active").as_bool();
        //skip this fluid if not active
        if (isActive)
        
            //read parameters
            ngl::Real volume = boost::lexical_cast<ngl::Real>(node.node().select_
      single_node("Volume").node().child_value());
            ngl::Real restDensity = boost::lexical_cast<ngl::Real>(node.node().se
      lect_single_node("RestDensity").node().child_value());
            tmp = getFloatVectorFromString(node.node().select_single_node("Colour
      ").node().attribute("value").value(), 3);
            ngl::Colour color(tmp[0], tmp[1], tmp[2]);
            std::string meshName = node.node().select_single_node("Obj").node().c
      hild_value();
            ngl::Obj mesh(meshName);
            tmp = getFloatVectorFromString(node.node().select_single_node("Obj").
      node().attribute("center").value(), 3);
            ngl::Vector centerOfMesh(tmp[0], tmp[1], tmp[2]);
            tmp = getFloatVectorFromString(node.node().select_single_node("Veloci
      ty").node().attribute("value").value(), 3);
            ngl::Vector velocity(tmp[0], tmp[1], tmp[2]);
            ngl::Real viscosityConstant = boost::lexical_cast<ngl::Real>(node.nod
      e().select_single_node("ViscosityConstant").node().child_value());
            ngl::Real gasConstant = boost::lexical_cast<ngl::Real>(node.node().se
      lect_single_node("GasConstant").node().child_value());
            ngl::Real surfaceTensionCoefficient = node.node().select_single_node(
      "SurfaceTension").node().attribute("coefficient").as_float();
            ngl::Real surfaceTensionThreshold = node.node().select_single_node("S
      urfaceTension").node().attribute("threshold").as_float();
            ngl::Real surfaceColorCoefficient = node.node().select_single_node("S
      urfaceTension").node().attribute("color").as_float();
            ngl::Real interfaceTensionCoefficient = node.node().select_single_nod
      e("SurfaceInterface").node().attribute("coefficient").as_float();
            ngl::Real interfaceTensionThreshold = node.node().select_single_node(
      "SurfaceInterface").node().attribute("threshold").as_float();
            ngl::Real interfaceColorCoefficient = node.node().select_single_node(
      "SurfaceInterface").node().attribute("color").as_float();
            ngl::Real collisionRadius = boost::lexical_cast<ngl::Real>(node.node(
      ).select_single_node("CollisionRadius").node().child_value());
            ngl::Real drawRadius = boost::lexical_cast<ngl::Real>(node.node().sel
      ect_single_node("DrawRadius").node().child_value());
            std::string name = node.node().attribute("name").value();
            //calculate mass per particle
            int particleCount = mesh.getNumVerts();
            ngl::Real mass = restDensity * (volume / ((ngl::Real)particleCount));
      
                for (int i = 0; i < particleCount; i++)
                
                    FluidParticle f = FluidParticle(
                                                        
      SimulationParameters::s_nextFluidParticleId++,
                                                        mass,
                                                        restDensity,
                                                        centerOfMesh + mesh.getVe
      rtexAtIndex(i),
                                                        velocity,
                                                        viscosityConstant,
                                                        gasConstant,
                                                        surfaceTensionCoefficient
      ,
                                                        surfaceTensionThreshold,
                                                        surfaceColorCoefficient,
                                                        interfaceTensionCoefficie
      nt,
                                                        interfaceTensionThreshold
      ,
                                                        interfaceColorCoefficient
      ,
                                                        color,
                                                        collisionRadius,
                                                        drawRadius,
                                                        name
                                                    );
                    //create particle @ mesh vertices and add to particle list
                    o_fluidParticleList.push_back (f);
                
                std::cout << "Fluid Name :: " << name << "Fluid Particles C
      ount :: " << particleCount << std::endl;
                o_fluidNameList.push_back(name);
        
    
    std::cout << "Number of Fluid Particles :: " << o_fluidParticleList.s
      ize() << "" <<std::endl;
Member Data Documentation
ngl::Real SimulationParameters::s_accelerationOfFreeFall = -9.28 [static]
acceleration due to gravity(free fall) value
Definition at line 29 of file SimulationParameters.h.
ngl::Colour SimulationParameters::s_boundaryColour [static]
colour of the boundry box
Definition at line 35 of file SimulationParameters.h.
bool SimulationParameters::s_debug = true [static]
debug parameter used in all the files to enable debugging and console output
Definition at line 26 of file SimulationParameters.h.
ngl::Real SimulationParameters::s_gravityAcceleration [static]
acceleration due to gravity(free fall) value
Definition at line 32 of file SimulationParameters.h.
int SimulationParameters::s_nextFluidParticleId = 0 [static]
global unique id available for creation of next particle in a fluid
Definition at line 38 of file SimulationParameters.h.
int SimulationParameters::s_nextRBDSphereId = -1 [static]
global unique id available for creation of next passive sphere rigid body
Definition at line 41 of file SimulationParameters.h.
std::string SimulationParameters::s_settingsDocumentPath = `SolverParameters/Settings.xml` [static, private]
the path of the configuration xml file
Definition at line 125 of file SimulationParameters.h.
The documentation for this class was generated from the following files:
include/SimulationParameters.h
src/SimulationParameters.cpp