EnvironmentAndRigidBody Class Reference
stores all rigid body spheres and boundary and manages collisions of fluids with rigid body spheres and Boundary Box
#include <EnvironmentAndRigidBody.h>
Public Member Functions
EnvironmentAndRigidBody ()
ctor
~EnvironmentAndRigidBody ()
dtor
void checkCollision (Particle &io_fluidParticle)
detects and handles collision among particles (sphere rbd and fluid particle)
bool getObstacleEnabled () const
returns whether RBD interaction is enabled
ngl::Real getBoundaryRestitutionCoefficientForFluid () const
returns the restitution coefficient for fluid interaction with boundary
ngl::Real getRBDSphereRestitutionCoefficient () const
return the restitution coefficient for fluid interaction with RBD
std::vector< Particle > & getRBDSphereList ()
return the list of passive Sphere Rigid Bodies
void setBoundaryRestitutionCoefficientForFluid (const ngl::Real _value)
set the restitution coefficient for fluid interaction with boundary
ngl::BBox * getBBox ()
return a pointer to Boundary Box
ngl::Colour getBoundaryColour ()
return the colour of Boundary Box required for Rendering
Private Member Functions
void checkAndSolveCollisionWithRBDSphere (Particle &io_fluidParticle, Particle &_rbdSphere)
handle collision between fluid and passive sphere rigid body
void checkAndSolveCollisionWithBoundary (Particle &io_fluidParticle)
handle collision between fluid and boundary box
Private Attributes
bool m_obstacleEnabled
flag to determine if RBD interaction is enabled
ngl::Vector m_boundaryDimension
boundary dimension
ngl::Vector m_boundaryPosition
boundary centre position
ngl::BBox * m_boundaryBBox
boundary bounding box object used for collision handling
ngl::Real m_boundaryRestitutionCoefficientForFluid
restitution coefficient for fluid interaction with boundary
ngl::Real m_rbdSphereRestitutionCoefficient
restitution coefficient for fluid interaction with RBD
std::vector< Particle > m_sphereRBDList
list of passive Sphere Rigid Bodies
ngl::Colour m_boundaryColour
colour for the Boundary Box
Detailed Description
stores all rigid body spheres and boundary and manages collisions of fluids with rigid body spheres and Boundary Box
Definition at line 17 of file EnvironmentAndRigidBody.h.
Constructor & Destructor Documentation
EnvironmentAndRigidBody::EnvironmentAndRigidBody ()
ctor
Definition at line 8 of file EnvironmentAndRigidBody.cpp.
References SimulationParameters::initialiseEnvironment(), m_boundaryBBox, m_boundaryColour, m_boundaryDimension, m_boundaryPosition, m_boundaryRestitutionCoefficientForFluid, m_obstacleEnabled, m_rbdSphereRestitutionCoefficient, and m_sphereRBDList.
    //create params from config
    SimulationParameters::initialiseEnvironment
                            (
                                m_obstacleEnabled,
                                m_boundaryPosition,
                                m_boundaryDimension,
                                m_boundaryRestitutionCoefficientForFluid,
                                m_sphereRBDList,
                                m_rbdSphereRestitutionCoefficient,
                                m_boundaryColour
                            );
    //create bbox for boundary
    m_boundaryBBox = new ngl::BBox(m_boundaryPosition, m_boundaryDimension.m_x,
      m_boundaryDimension.m_y, m_boundaryDimension.m_z);
EnvironmentAndRigidBody::~EnvironmentAndRigidBody ()
dtor
Definition at line 26 of file EnvironmentAndRigidBody.cpp.
References m_boundaryBBox.
    //clean up
    std::cout << "EnvironmentAndRigidBody Cleanup" << std::endl;
    delete m_boundaryBBox;
Member Function Documentation
void EnvironmentAndRigidBody::checkAndSolveCollisionWithBoundary (Particle & io_fluidParticle) [private]
handle collision between fluid and boundary box
Parameters
$\leftrightarrow$ io_fluidParticle the particle affected by the collision resolution
Definition at line 89 of file EnvironmentAndRigidBody.cpp.
References Particle::getCollisionRadius(), Particle::getCurrentPosition(), Particle::getCurrentVelocity(), Particle::updatePosition(), and Particle::updateVelocity().
    //determine bounds of box
    ngl::Real xMax = m_boundaryBBox->center().m_x + (m_boundaryBBox->width()/2.0f
      );
    ngl::Real xMin = m_boundaryBBox->center().m_x - (m_boundaryBBox->width()/2.0f
      );
    ngl::Real yMax = m_boundaryBBox->center().m_y + (m_boundaryBBox->height()/2.0
      f);
    ngl::Real yMin = m_boundaryBBox->center().m_y - (m_boundaryBBox->height()/2.0
      f);
    ngl::Real zMax = m_boundaryBBox->center().m_z + (m_boundaryBBox->depth()/2.0f
      );
    ngl::Real zMin = m_boundaryBBox->center().m_z - (m_boundaryBBox->depth()/2.0f
      );
    //move bounds closer due to difference in particle radius
    xMax -= io_fluidParticle.getCollisionRadius();
    xMin += io_fluidParticle.getCollisionRadius();
    yMax -= io_fluidParticle.getCollisionRadius();
    yMin += io_fluidParticle.getCollisionRadius();
    zMax -= io_fluidParticle.getCollisionRadius();
    zMin += io_fluidParticle.getCollisionRadius();
    //get position of particle
    ngl::Vector currentPosition = io_fluidParticle.getCurrentPosition();
    ngl::Real restitutionCoefficient = m_boundaryRestitutionCoefficientForFluid;
    if (currentPosition.m_x > xMax)
    
        //set position to boundary edge
        io_fluidParticle.updatePosition(ngl::Vector(xMax, io_fluidParticle.
      getCurrentPosition().m_y, io_fluidParticle.getCurrentPosition().m_z));
        //calculate new velocity (reflect on face normal with restitution factor
        io_fluidParticle.updateVelocity(ngl::Vector(-restitutionCoefficient * io_
      fluidParticle.getCurrentVelocity().m_x, io_fluidParticle.getCurrentVelocity().m_y
      , io_fluidParticle.getCurrentVelocity().m_z));
    
    if (currentPosition.m_x < xMin)
    
        //set position to boundary edge
        io_fluidParticle.updatePosition(ngl::Vector(xMin, io_fluidParticle.
      getCurrentPosition().m_y, io_fluidParticle.getCurrentPosition().m_z));
        //calculate new velocity (reflect on face normal with restitution factor
        io_fluidParticle.updateVelocity(ngl::Vector(-restitutionCoefficient * io_
      fluidParticle.getCurrentVelocity().m_x, io_fluidParticle.getCurrentVelocity().m_y
      , io_fluidParticle.getCurrentVelocity().m_z));
    
    if (currentPosition.m_y > yMax)
    
        //set position to boundary edge
        io_fluidParticle.updatePosition(ngl::Vector(io_fluidParticle.
      getCurrentPosition().m_x, yMax, io_fluidParticle.getCurrentPosition().m_z));
        //calculate new velocity (reflect on face normal with restitution factor
        io_fluidParticle.updateVelocity(ngl::Vector(io_fluidParticle.
      getCurrentVelocity().m_x, -restitutionCoefficient * io_fluidParticle.
      getCurrentVelocity().m_y, io_fluidParticle.getCurrentVelocity().m_z));
    
    if (currentPosition.m_y < yMin)
    
        //set position to boundary edge
        io_fluidParticle.updatePosition(ngl::Vector(io_fluidParticle.
      getCurrentPosition().m_x, yMin, io_fluidParticle.getCurrentPosition().m_z));
        //calculate new velocity (reflect on face normal with restitution factor
        io_fluidParticle.updateVelocity(ngl::Vector(io_fluidParticle.
      getCurrentVelocity().m_x, -restitutionCoefficient * io_fluidParticle.
      getCurrentVelocity().m_y, io_fluidParticle.getCurrentVelocity().m_z));
    
    if (currentPosition.m_z > zMax)
    
        io_fluidParticle.updatePosition(ngl::Vector(io_fluidParticle.
      getCurrentPosition().m_x, io_fluidParticle.getCurrentPosition().m_y, zMax));
        //calculate new velocity (reflect on face normal with restitution factor
        io_fluidParticle.updateVelocity(ngl::Vector(io_fluidParticle.
      getCurrentVelocity().m_x, io_fluidParticle.getCurrentVelocity().m_y, -restitution
      Coefficient * io_fluidParticle.getCurrentVelocity().m_z));
    
    if (currentPosition.m_z < zMin)
    
        io_fluidParticle.updatePosition(ngl::Vector(io_fluidParticle.
      getCurrentPosition().m_x, io_fluidParticle.getCurrentPosition().m_y, zMin));
        //calculate new velocity (reflect on face normal with restitution factor
        io_fluidParticle.updateVelocity(ngl::Vector(io_fluidParticle.
      getCurrentVelocity().m_x, io_fluidParticle.getCurrentVelocity().m_y, -restitution
      Coefficient * io_fluidParticle.getCurrentVelocity().m_z));
    
void EnvironmentAndRigidBody::checkAndSolveCollisionWithRBDSphere (Particle & io_fluidParticle, Particle & _rbdSphere) [private]
handle collision between fluid and passive sphere rigid body
Parameters
$\leftrightarrow$ io_fluidParticle the particle affected by the collision resolution
$\leftarrow$ _rbdSphere the rigid body sphere against which collision is checked
Definition at line 52 of file EnvironmentAndRigidBody.cpp.
References Particle::getCollisionRadius(), Particle::getCurrentPosition(), Particle::getCurrentVelocity(), Particle::updatePosition(), and Particle::updateVelocity().
    ngl::Real restitutionCoefficient = m_rbdSphereRestitutionCoefficient;
    //initialise variables
    ngl::Vector X = io_fluidParticle.getCurrentPosition();
    ngl::Vector C = _rbdSphere.getCurrentPosition();
    ngl::Vector XC = X - C;
    ngl::Vector CX = C - X;
    ngl::Real r = io_fluidParticle.getCollisionRadius() + _rbdSphere.
      getCollisionRadius();
    //calculate implicit function value for a sphere
    ngl::Real Fx = XC.lengthSquared() - (r * r);
    if (Fx < 0)
    
        //calculate contact point
        ngl::Vector CP = C + (r * (XC / XC.length()));
        //calculate normal
        ngl::Vector n = (Fx < 0 ? -1 : Fx == 0 ? 0 : 1) * (CX / CX.length());
        io_fluidParticle.updatePosition(CP);
        ngl::Real dot = n.dot(io_fluidParticle.getCurrentVelocity());
        ngl::Vector vel = io_fluidParticle.getCurrentVelocity() - ((1.0 + restitu
      tionCoefficient) * dot * n);
        io_fluidParticle.updateVelocity(vel);
    
void EnvironmentAndRigidBody::checkCollision (Particle & io_fluidParticle)
detects and handles collision among particles (sphere rbd and fluid particle)
Parameters
$\leftrightarrow$ io_fluidParticle checks for collision with boundary and rigidbody
Definition at line 35 of file EnvironmentAndRigidBody.cpp.
References checkAndSolveCollisionWithBoundary(), checkAndSolveCollisionWithRBDSphere(), m_obstacleEnabled, and m_sphereRBDList.
    if (m_obstacleEnabled)
    
        BOOST_FOREACH(Particle& rbdSphere, m_sphereRBDList)
        
                /*-------Check Collisions against Rigid Body Spheres-------------
      -------*/
                checkAndSolveCollisionWithRBDSphere(io_fluidParticle, rbdSphere);
      
        
     
    /*-----------Check Collision against the Boundry Box------------------*/
    checkAndSolveCollisionWithBoundary(io_fluidParticle);
ngl::BBox* EnvironmentAndRigidBody::getBBox () [inline]
return a pointer to Boundary Box
Definition at line 50 of file EnvironmentAndRigidBody.h.
References m_boundaryBBox.
return m_boundaryBBox;
ngl::Colour EnvironmentAndRigidBody::getBoundaryColour () [inline]
return the colour of Boundary Box required for Rendering
Definition at line 53 of file EnvironmentAndRigidBody.h.
References m_boundaryColour.
return m_boundaryColour;
ngl::Real EnvironmentAndRigidBody::getBoundaryRestitutionCoefficientForFluid () const [inline]
returns the restitution coefficient for fluid interaction with boundary
Definition at line 37 of file EnvironmentAndRigidBody.h.
References m_boundaryRestitutionCoefficientForFluid.
 return m_boundaryRestitutionCoefficientForFluid;
bool EnvironmentAndRigidBody::getObstacleEnabled () const [inline]
returns whether RBD interaction is enabled
Definition at line 34 of file EnvironmentAndRigidBody.h.
References m_obstacleEnabled.
 return m_obstacleEnabled;
std::vector<Particle>& EnvironmentAndRigidBody::getRBDSphereList () [inline]
return the list of passive Sphere Rigid Bodies
Definition at line 43 of file EnvironmentAndRigidBody.h.
References m_sphereRBDList.
 return m_sphereRBDList;
ngl::Real EnvironmentAndRigidBody::getRBDSphereRestitutionCoefficient () const [inline]
return the restitution coefficient for fluid interaction with RBD
Definition at line 40 of file EnvironmentAndRigidBody.h.
References m_rbdSphereRestitutionCoefficient.
 return m_rbdSphereRestitutionCoefficient;
void EnvironmentAndRigidBody::setBoundaryRestitutionCoefficientForFluid (const ngl::Real _value) [inline]
set the restitution coefficient for fluid interaction with boundary
Parameters
$\leftarrow$ _value the new value
Definition at line 47 of file EnvironmentAndRigidBody.h.
References m_boundaryRestitutionCoefficientForFluid.
 m_boundaryRestitutionCoefficientForFluid = _value;
Member Data Documentation
ngl::BBox* EnvironmentAndRigidBody::m_boundaryBBox [private]
boundary bounding box object used for collision handling
Definition at line 67 of file EnvironmentAndRigidBody.h.
ngl::Colour EnvironmentAndRigidBody::m_boundaryColour [private]
colour for the Boundary Box
Definition at line 79 of file EnvironmentAndRigidBody.h.
ngl::Vector EnvironmentAndRigidBody::m_boundaryDimension [private]
boundary dimension
Definition at line 61 of file EnvironmentAndRigidBody.h.
ngl::Vector EnvironmentAndRigidBody::m_boundaryPosition [private]
boundary centre position
Definition at line 64 of file EnvironmentAndRigidBody.h.
ngl::Real EnvironmentAndRigidBody::m_boundaryRestitutionCoefficientForFluid [private]
restitution coefficient for fluid interaction with boundary
Definition at line 70 of file EnvironmentAndRigidBody.h.
bool EnvironmentAndRigidBody::m_obstacleEnabled [private]
flag to determine if RBD interaction is enabled
Definition at line 58 of file EnvironmentAndRigidBody.h.
ngl::Real EnvironmentAndRigidBody::m_rbdSphereRestitutionCoefficient [private]
restitution coefficient for fluid interaction with RBD
Definition at line 73 of file EnvironmentAndRigidBody.h.
std::vector<Particle> EnvironmentAndRigidBody::m_sphereRBDList [private]
list of passive Sphere Rigid Bodies
Definition at line 76 of file EnvironmentAndRigidBody.h.
The documentation for this class was generated from the following files:
include/EnvironmentAndRigidBody.h
src/EnvironmentAndRigidBody.cpp